//! Storage and infrastructure boundaries for authenticated Phase 2.

use argon2::{
    password_hash::{rand_core::OsRng, SaltString},
    Argon2, Params, PasswordHash, PasswordHasher, PasswordVerifier,
};
use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine};
use coop_cloud::{
    CharacterCloudState, CharacterId, ClientInstanceId, CommitId, Group, GroupId,
    GroupInvitationId, GroupRomHandoffArrivalRequest, GroupRomHandoffIntent, GroupRomHandoffSource,
    GroupTravelProposalId, GroupTravelProposalView, IdempotencyKey, LeaseContract, RefreshFamilyId,
    Revision, RomHandoffCommitRequest, RomHandoffPrepareRequest, RuntimeBuildIdentity,
    RuntimeLeaseFence, SessionId, Sha256Digest, SigningPrivateKey, SnapshotFile,
    SnapshotFinalizeRequest, SnapshotId, SnapshotPrepareRequest, SnapshotRecord,
    SnapshotRestoreRequest, StableRuntimeSession, UnixTimestampMillis, UploadTarget, UserId,
    MAX_WORLD_REVISION,
};
use coop_protocol::{RegionId, RegionalProgress, RomWorldId, WorldZone};
use getrandom::fill as random_fill;
use hmac::Mac;
use serde::de::{MapAccess, Visitor};
use sha2::{Digest, Sha256};
use std::{
    collections::{BTreeMap, HashMap, HashSet},
    fmt,
    sync::atomic::{AtomicU64, Ordering},
    sync::{Arc, RwLock},
    time::{Duration, Instant, SystemTime, UNIX_EPOCH},
};
use thiserror::Error;
use uuid::Uuid;
use zeroize::Zeroizing;

pub const ACCESS_TTL_MS: u64 = 15 * 60 * 1_000;
pub const REFRESH_TTL_MS: u64 = 30 * 24 * 60 * 60 * 1_000;
pub const HEARTBEAT_INTERVAL_MS: u32 = 10_000;
pub const LEASE_TTL_MS: u64 = 30_000;
pub const RECONNECT_GRACE_MS: u64 = 90_000;
pub const UPLOAD_TTL_MS: u64 = 5 * 60 * 1_000;
pub const MAX_CHARACTER_SAV: u64 =
    (coop_save::FLASH_IMAGE_SIZE + coop_save::RTC_TRAILER_SIZE) as u64;
pub const MAX_PENDING_COMMITS: u64 = 1_048_576;
pub const MAX_RESUME_SS1: u64 = 32 * 1_048_576;
pub const MAX_RESUME_RESPONSE: u64 = 40 * 1_048_576;
pub const MAX_PREPARED_SNAPSHOTS: usize = 128;
pub const MAX_UPLOAD_TICKETS: usize = 384;
pub const MAX_SNAPSHOTS_PER_CHARACTER: usize = 100;
pub const MAX_SNAPSHOT_STORAGE_BYTES: u64 = 256 * 1024 * 1024;
/// Retired snapshot IDs are a bounded replay-defense cache. Snapshot IDs are
/// UUIDs generated by the server/client protocol; live snapshots and
/// operations remain authoritative after an old tombstone is evicted.
pub const MAX_RETIRED_SNAPSHOTS: usize = 1_024;
pub const MAX_RELEASE_KEYS: usize = 256;
pub const ACQUIRE_IDEMPOTENCY_TTL_MS: u64 = 24 * 60 * 60 * 1_000;
pub const MAX_ACQUIRE_HISTORY: usize = 256;
pub const RESTORE_STAGE_TTL_MS: u64 = 5 * 60 * 1_000;
pub const ROM_HANDOFF_STAGE_TTL_MS: u64 = 5 * 60 * 1_000;
/// A source head can have only a bounded number of aborted handoff intents.
/// Keeping these request tombstones until the source head advances closes the
/// delayed-prepare replay window without allowing unbounded client growth.
pub const MAX_ROM_HANDOFF_ABORT_TOMBSTONES_PER_CHARACTER: usize = 64;
pub const MAX_ACCESS_RECORDS_PER_CHARACTER: usize = 1_024;
pub const MAX_REFRESH_RECORDS_PER_CHARACTER: usize = 1_024;
pub const MAX_FAMILY_RECORDS_PER_CHARACTER: usize = 128;
pub const MAX_ACCESS_RECORDS_GLOBAL: usize = 16_384;
pub const MAX_REFRESH_RECORDS_GLOBAL: usize = 16_384;
pub const MAX_FAMILY_RECORDS_GLOBAL: usize = 4_096;
/// Maximum number of unexpired realtime capabilities retained by one local
/// server process.
pub const MAX_REALTIME_TICKETS_GLOBAL: usize = 1_024;
pub const GROUP_INVITATION_TTL_MS: u64 = coop_cloud::GROUP_INVITATION_TTL_MS;
pub const MAX_GROUP_INVITATIONS: usize = 1_024;
pub const MAX_GROUP_IDEMPOTENCY: usize = 4_096;
pub const GROUP_IDEMPOTENCY_TTL_MS: u64 = 24 * 60 * 60 * 1_000;
pub const MAX_GROUP_ROM_HANDOFF_STAGES: usize = 1_024;
pub const MAX_GROUP_ROM_HANDOFF_RECEIPTS: usize = 4_096;
/// Terminal paired-handoff receipts are replay tombstones, not an unbounded
/// audit log. They remain available for this recovery window; a client must
/// deliberately use a new `client_intent_key` after it expires.
pub const GROUP_ROM_HANDOFF_RECEIPT_RETENTION_MS: u64 = 24 * 60 * 60 * 1_000;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum StorageMode {
    Phase2Local,
    PostgresFirebase,
}

#[derive(Clone, Debug, Eq, Error, PartialEq)]
pub enum StorageError {
    #[error("entropy source unavailable")]
    Entropy,
    #[error("clock value is outside the supported range")]
    Clock,
    #[error("production adapters are unavailable")]
    ProductionUnavailable,
    #[error("state lock unavailable")]
    Lock,
    #[error("invalid storage configuration")]
    InvalidConfiguration,
    #[error("password engine unavailable")]
    Password,
    #[error("repository transaction failed")]
    Transaction,
    #[error("persistent repository is fenced")]
    Persistence,
    #[error("storage worker is busy")]
    Busy,
    #[error("persistent state exceeds its size limit")]
    StateTooLarge,
}

/// Password hashing and verification boundary. Implementations must use a
/// memory-hard password hash and should be configured with a test-only policy
/// when deterministic tests need a lower-cost operation.
pub trait PasswordEngine: Send + Sync {
    /// Hashes a password into a PHC string.
    ///
    /// # Errors
    ///
    /// Returns an error when the configured password engine cannot hash.
    fn hash(&self, password: &str) -> Result<String, StorageError>;
    /// Verifies a password against a PHC string without exposing parse errors.
    fn verify(&self, password: &str, phc: &str) -> bool;
    /// Returns a PHC dummy used to equalize unknown-user login work.
    fn dummy_phc(&self) -> &str;
}

/// Argon2id password engine used by local mode and injectable in tests.
pub struct ArgonPasswordEngine {
    params: Params,
    dummy_phc: String,
}

impl ArgonPasswordEngine {
    /// Creates an Argon2id engine with an explicit resource policy.
    ///
    /// # Errors
    ///
    /// Returns an error when Argon2 rejects the requested parameters.
    pub fn new(memory_kib: u32, iterations: u32, lanes: u32) -> Result<Self, StorageError> {
        let params =
            Params::new(memory_kib, iterations, lanes, None).map_err(|_| StorageError::Password)?;
        let engine = Self {
            params,
            dummy_phc: String::new(),
        };
        let dummy_phc = engine.hash_with_salt("dummy password")?;
        Ok(Self {
            dummy_phc,
            ..engine
        })
    }

    /// Creates the production policy (19,456 KiB, two iterations, one lane).
    ///
    /// # Panics
    ///
    /// Panics only if the compile-time production Argon2 parameters are
    /// rejected by the Argon2 library.
    #[must_use]
    pub fn production() -> Self {
        let params = Params::new(19_456, 2, 1, None).expect("production Argon2 policy");
        Self {
            params,
            dummy_phc: "$argon2id$v=19$m=19456,t=2,p=1$sUqdATt6cZlDUSAFETIqxg$6wHrJVz2ilL92GTlXsq86hF4iMX551k2AFNf004LDvY".to_owned(),
        }
    }

    fn argon(&self) -> Argon2<'static> {
        Argon2::new(
            argon2::Algorithm::Argon2id,
            argon2::Version::V0x13,
            self.params.clone(),
        )
    }

    fn hash_with_salt(&self, password: &str) -> Result<String, StorageError> {
        let salt = SaltString::generate(&mut OsRng);
        self.argon()
            .hash_password(password.as_bytes(), &salt)
            .map(|hash| hash.to_string())
            .map_err(|_| StorageError::Password)
    }
}

impl PasswordEngine for ArgonPasswordEngine {
    fn hash(&self, password: &str) -> Result<String, StorageError> {
        self.hash_with_salt(password)
    }

    fn verify(&self, password: &str, phc: &str) -> bool {
        let Ok(hash) = PasswordHash::new(phc) else {
            return false;
        };
        self.argon()
            .verify_password(password.as_bytes(), &hash)
            .is_ok()
    }

    fn dummy_phc(&self) -> &str {
        &self.dummy_phc
    }
}

pub trait Clock: Send + Sync {
    /// Returns server-owned Unix milliseconds.
    fn now_ms(&self) -> u64;
}
pub trait Entropy: Send + Sync {
    /// Fills a buffer with cryptographically suitable bytes.
    ///
    /// # Errors
    ///
    /// Returns an infrastructure error when entropy cannot be obtained.
    fn fill(&self, bytes: &mut [u8]) -> Result<(), StorageError>;
}

/// Atomic state repository boundary used by the Phase 2 service.
///
/// Both the in-memory and pilot `PostgreSQL` adapters preserve this whole-state
/// boundary, including mutations made before a callback returns an error.
pub trait Repository: Send + Sync {
    /// Probes readiness without requiring a full state read when supported.
    fn check_ready(&self) -> Result<(), StorageError> {
        self.read_transaction(&mut |_| Ok(()))
    }

    /// Runs a short read-only repository operation atomically. Adapters with
    /// a real transaction engine override this method; the local adapter
    /// provides the same boundary with its process-local lock.
    ///
    /// # Errors
    ///
    /// Returns an adapter error when the transaction cannot be opened or the
    /// operation fails.
    fn read_transaction(
        &self,
        operation: &mut dyn FnMut(&State) -> Result<(), StorageError>,
    ) -> Result<(), StorageError>;

    /// Runs a short state transition atomically. Object-store work is not
    /// permitted in the callback.
    ///
    /// # Errors
    ///
    /// Returns an adapter error when the transaction cannot be opened or the
    /// operation fails.
    fn write_transaction(
        &self,
        operation: &mut dyn FnMut(&mut State) -> Result<(), StorageError>,
    ) -> Result<(), StorageError>;

    /// Reports whether the adapter fenced itself after losing its backend.
    /// A fenced process needs a restart; anything else recovers on its own.
    /// The default is never fenced.
    fn is_fenced(&self) -> bool {
        false
    }
}

/// Immutable-artifact object-store boundary used by snapshot operations.
pub trait ObjectStore: Send + Sync {
    /// Reports a permanently failed backend worker to process readiness.
    fn is_fenced(&self) -> bool {
        false
    }
    /// Permanently fences an absent key against later publication. Returns
    /// true for a newly installed or existing retirement fence, false for a
    /// live object. Reads/deletes must never expose/remove retirement fences.
    ///
    /// # Errors
    /// Returns an error if atomic retirement is unavailable.
    fn retire_if_absent(&self, _key: &str) -> Result<bool, StorageError> {
        Err(StorageError::Transaction)
    }
    /// Reads an object by its server-derived key.
    ///
    /// # Errors
    ///
    /// Returns [`StorageError::Lock`] when the adapter cannot access its state.
    fn get(&self, key: &str) -> Result<Option<Vec<u8>>, StorageError>;
    /// Writes an object under a server-derived key.
    ///
    /// # Errors
    ///
    /// Returns [`StorageError::Lock`] when the adapter cannot access its state.
    fn put(&self, key: String, bytes: Vec<u8>) -> Result<(), StorageError>;
    /// Atomically creates an object if the key is absent. Implementations
    /// backed by a remote store must map this to a conditional create. The
    /// default fails closed because a contains-then-put sequence is not an
    /// atomic create under concurrency.
    ///
    /// # Errors
    ///
    /// Returns an adapter error when the existence check or write fails.
    fn put_if_absent(&self, key: String, bytes: Vec<u8>) -> Result<bool, StorageError> {
        let _ = (key, bytes);
        Err(StorageError::Transaction)
    }
    /// Deletes an object during failed staged publication. Implementations
    /// backed by a remote store must make this operation idempotent.
    ///
    /// # Errors
    ///
    /// Returns an adapter error when the object cannot be removed.
    fn delete_if_present(&self, key: &str) -> Result<bool, StorageError> {
        let _ = key;
        Err(StorageError::Transaction)
    }
    /// Checks whether an object exists.
    ///
    /// # Errors
    ///
    /// Returns [`StorageError::Lock`] when the adapter cannot access its state.
    fn contains(&self, key: &str) -> Result<bool, StorageError>;
}

/// Process-local repository adapter for deterministic tests and local mode.
#[derive(Clone, Default)]
pub struct InMemoryRepository {
    state: Arc<RwLock<State>>,
}

impl InMemoryRepository {
    /// Creates an empty in-memory repository.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }
}

impl Repository for InMemoryRepository {
    fn read_transaction(
        &self,
        operation: &mut dyn FnMut(&State) -> Result<(), StorageError>,
    ) -> Result<(), StorageError> {
        let state = self.state.read().map_err(|_| StorageError::Lock)?;
        operation(&state)
    }

    fn write_transaction(
        &self,
        operation: &mut dyn FnMut(&mut State) -> Result<(), StorageError>,
    ) -> Result<(), StorageError> {
        let mut state = self.state.write().map_err(|_| StorageError::Lock)?;
        operation(&mut state)
    }
}

/// Process-local object-store adapter for fixed snapshot artifacts.
#[derive(Clone, Default)]
pub struct InMemoryObjectStore {
    objects: Arc<RwLock<HashMap<String, Option<Vec<u8>>>>>,
}

impl InMemoryObjectStore {
    /// Creates an empty in-memory object store.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    #[cfg(test)]
    pub(crate) fn object_count(&self) -> Result<usize, StorageError> {
        Ok(self
            .objects
            .read()
            .map_err(|_| StorageError::Lock)?
            .values()
            .filter(|value| value.is_some())
            .count())
    }
}

impl ObjectStore for InMemoryObjectStore {
    fn retire_if_absent(&self, key: &str) -> Result<bool, StorageError> {
        let mut objects = self.objects.write().map_err(|_| StorageError::Lock)?;
        Ok(objects.entry(key.to_owned()).or_insert(None).is_none())
    }
    fn get(&self, key: &str) -> Result<Option<Vec<u8>>, StorageError> {
        self.objects
            .read()
            .map_err(|_| StorageError::Lock)
            .map(|objects| objects.get(key).cloned().flatten())
    }

    fn put(&self, key: String, bytes: Vec<u8>) -> Result<(), StorageError> {
        let mut objects = self.objects.write().map_err(|_| StorageError::Lock)?;
        if objects.get(&key).is_some_and(Option::is_none) {
            return Err(StorageError::Transaction);
        }
        objects.insert(key, Some(bytes));
        Ok(())
    }

    fn put_if_absent(&self, key: String, bytes: Vec<u8>) -> Result<bool, StorageError> {
        let mut objects = self.objects.write().map_err(|_| StorageError::Lock)?;
        if objects.contains_key(&key) {
            return Ok(false);
        }
        objects.insert(key, Some(bytes));
        Ok(true)
    }

    fn delete_if_present(&self, key: &str) -> Result<bool, StorageError> {
        let mut objects = self.objects.write().map_err(|_| StorageError::Lock)?;
        if objects.get(key).is_some_and(Option::is_some) {
            objects.remove(key);
            return Ok(true);
        }
        Ok(false)
    }

    fn contains(&self, key: &str) -> Result<bool, StorageError> {
        self.objects
            .read()
            .map_err(|_| StorageError::Lock)
            .map(|objects| objects.get(key).is_some_and(Option::is_some))
    }
}

#[derive(Clone, Copy, Debug, Default)]
pub struct SystemClock;
static LAST_SYSTEM_CLOCK_MS: AtomicU64 = AtomicU64::new(0);
impl Clock for SystemClock {
    fn now_ms(&self) -> u64 {
        let observed = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map_or(u64::MAX, |d| d.as_millis().try_into().unwrap_or(u64::MAX));
        let mut previous = LAST_SYSTEM_CLOCK_MS.load(Ordering::Acquire);
        loop {
            if observed <= previous {
                return previous;
            }
            match LAST_SYSTEM_CLOCK_MS.compare_exchange_weak(
                previous,
                observed,
                Ordering::AcqRel,
                Ordering::Acquire,
            ) {
                Ok(_) => return observed,
                Err(current) => previous = current,
            }
        }
    }
}
#[derive(Clone, Copy, Debug, Default)]
pub struct OsEntropy;
impl Entropy for OsEntropy {
    fn fill(&self, bytes: &mut [u8]) -> Result<(), StorageError> {
        random_fill(bytes).map_err(|_| StorageError::Entropy)
    }
}

#[cfg(test)]
#[derive(Debug)]
pub struct FixedClock(std::sync::atomic::AtomicU64);
#[cfg(test)]
impl FixedClock {
    /// Creates a clock at a fixed Unix millisecond value.
    #[must_use]
    pub fn new(ms: u64) -> Self {
        Self(std::sync::atomic::AtomicU64::new(ms))
    }
    /// Replaces the current time.
    pub fn set(&self, ms: u64) {
        self.0.store(ms, std::sync::atomic::Ordering::SeqCst);
    }
    /// Advances the current time.
    pub fn advance(&self, ms: u64) {
        self.0.fetch_add(ms, std::sync::atomic::Ordering::SeqCst);
    }
}
#[cfg(test)]
impl Clock for FixedClock {
    fn now_ms(&self) -> u64 {
        self.0.load(std::sync::atomic::Ordering::SeqCst)
    }
}

#[cfg(test)]
#[derive(Debug)]
pub struct FixedEntropy {
    bytes: Vec<u8>,
    cursor: std::sync::Mutex<usize>,
}
#[cfg(test)]
impl FixedEntropy {
    /// Creates a repeating deterministic byte source for tests.
    #[must_use]
    pub fn new(bytes: Vec<u8>) -> Self {
        Self {
            bytes,
            cursor: std::sync::Mutex::new(0),
        }
    }
}
#[cfg(test)]
impl Entropy for FixedEntropy {
    fn fill(&self, output: &mut [u8]) -> Result<(), StorageError> {
        let mut cursor = self.cursor.lock().map_err(|_| StorageError::Lock)?;
        if self.bytes.is_empty() {
            return Err(StorageError::Entropy);
        }
        for byte in output {
            *byte = self.bytes[*cursor % self.bytes.len()];
            *cursor = cursor.saturating_add(1);
        }
        Ok(())
    }
}

/// Explicit server configuration for the Phase 2 adapters.
#[derive(Clone)]
pub struct Phase2Config {
    pub(crate) mode: StorageMode,
    pub(crate) invite_pepper: Zeroizing<Vec<u8>>,
    pub(crate) signing_key: SigningPrivateKey,
    pub(crate) signing_key_id: String,
    pub(crate) upload_base_url: String,
    pub(crate) clock: Arc<dyn Clock>,
    pub(crate) entropy: Arc<dyn Entropy>,
    pub(crate) password_engine: Arc<dyn PasswordEngine>,
    pub(crate) repository: Option<Arc<dyn Repository>>,
    pub(crate) object_store: Option<Arc<dyn ObjectStore>>,
    pub(crate) production: Option<ProductionConfig>,
    pub(crate) release_catalog: Option<Arc<super::saves::build_catalog::TrustedBuildCatalog>>,
    #[cfg(test)]
    pub(crate) fixture_auto_bind: bool,
}

/// Validated connection identifiers required by the production adapters.
/// Production startup also requires mounted secrets and concrete adapters.
#[derive(Clone, Eq, PartialEq)]
pub struct ProductionConfig {
    pub database_url: String,
    pub firebase_bucket: String,
}

impl fmt::Debug for ProductionConfig {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("ProductionConfig([REDACTED])")
    }
}

impl ProductionConfig {
    /// Creates validated production connection identifiers.
    ///
    /// # Errors
    ///
    /// Returns [`StorageError::InvalidConfiguration`] for empty or oversized
    /// connection identifiers.
    pub fn new(
        database_url: impl Into<String>,
        firebase_bucket: impl Into<String>,
    ) -> Result<Self, StorageError> {
        let database_url = database_url.into();
        let firebase_bucket = firebase_bucket.into();
        let config = Self {
            database_url,
            firebase_bucket,
        };
        config.validate()
    }

    fn validate(self) -> Result<Self, StorageError> {
        let database =
            url::Url::parse(&self.database_url).map_err(|_| StorageError::InvalidConfiguration)?;
        let valid_database_scheme = matches!(database.scheme(), "postgres" | "postgresql");
        let valid_bucket = !self.firebase_bucket.is_empty()
            && self.firebase_bucket.len() <= 512
            && self
                .firebase_bucket
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'-' | b'_'));
        if !valid_database_scheme
            || database.host_str().is_none_or(str::is_empty)
            || self.database_url.len() > 4096
            || !valid_bucket
        {
            return Err(StorageError::InvalidConfiguration);
        }
        Ok(self)
    }
}

/// Explicit marker for a PostgreSQL-backed repository adapter.
pub trait PostgresRepository: Repository {}
/// Explicit marker for a Firebase-backed immutable object-store adapter.
pub trait FirebaseObjectStore: ObjectStore {}
impl Phase2Config {
    #[cfg(test)]
    pub(crate) fn with_legacy_test_runtime(mut self) -> Self {
        let build = super::saves::current_runtime_build_identity().expect("test build manifest");
        let bytes = serde_json::to_vec(&serde_json::json!({
            "schema_version": 1,
            "worlds": [{"world_id": 1, "build": build}]
        }))
        .expect("test catalog JSON");
        self = self
            .with_release_catalog_bytes(&bytes, Sha256Digest::of_bytes(&bytes))
            .expect("test catalog");
        self.fixture_auto_bind = true;
        self
    }

    /// Install a release catalog whose exact bytes match a separately trusted
    /// digest. The caller must obtain the digest from release configuration,
    /// never from the same client request as the catalog bytes.
    ///
    /// # Errors
    /// Returns invalid configuration for a digest or catalog mismatch.
    pub fn with_release_catalog_bytes(
        mut self,
        bytes: &[u8],
        trusted_digest: Sha256Digest,
    ) -> Result<Self, StorageError> {
        let catalog = super::saves::build_catalog::TrustedBuildCatalog::from_release_bytes(
            bytes,
            trusted_digest,
        )
        .map_err(|_| StorageError::InvalidConfiguration)?;
        self.release_catalog = Some(Arc::new(catalog));
        Ok(self)
    }

    /// Install a pinned travel catalog and cache its release-owned arrival
    /// images after digest, save-format, and map-location validation.
    pub fn with_release_catalog_and_arrival_saves(
        mut self,
        bytes: &[u8],
        trusted_digest: Sha256Digest,
        release_root: &std::path::Path,
    ) -> Result<Self, StorageError> {
        let mut catalog = super::saves::build_catalog::TrustedBuildCatalog::from_release_bytes(
            bytes,
            trusted_digest,
        )
        .map_err(|_| StorageError::InvalidConfiguration)?;
        catalog
            .load_arrival_saves(release_root)
            .map_err(|_| StorageError::InvalidConfiguration)?;
        self.release_catalog = Some(Arc::new(catalog));
        Ok(self)
    }

    /// Creates a loopback-only local configuration with supplied secrets.
    ///
    /// # Errors
    ///
    /// Returns an error when the pepper is too short.
    pub fn local(
        pepper: impl Into<Vec<u8>>,
        signing_key: SigningPrivateKey,
        key_id: impl Into<String>,
    ) -> Result<Self, StorageError> {
        let pepper = pepper.into();
        let signing_key_id = key_id.into();
        if pepper.len() < 16 {
            return Err(StorageError::Entropy);
        }
        if !valid_key_id(&signing_key_id) {
            return Err(StorageError::InvalidConfiguration);
        }
        Ok(Self {
            mode: StorageMode::Phase2Local,
            invite_pepper: Zeroizing::new(pepper),
            signing_key,
            signing_key_id,
            upload_base_url: "http://127.0.0.1".to_owned(),
            clock: Arc::new(SystemClock),
            entropy: Arc::new(OsEntropy),
            password_engine: Arc::new(ArgonPasswordEngine::production()),
            repository: None,
            object_store: None,
            production: None,
            release_catalog: None,
            #[cfg(test)]
            fixture_auto_bind: false,
        })
    }
    /// Selects persistent mode without secrets or adapters. This incomplete
    /// configuration fails closed; the production entry point fills it in.
    #[must_use]
    pub fn postgres_firebase() -> Self {
        Self {
            mode: StorageMode::PostgresFirebase,
            invite_pepper: Zeroizing::new(Vec::new()),
            signing_key: SigningPrivateKey::from_bytes([0; 32]),
            signing_key_id: String::new(),
            upload_base_url: String::new(),
            clock: Arc::new(SystemClock),
            entropy: Arc::new(OsEntropy),
            password_engine: Arc::new(ArgonPasswordEngine::production()),
            repository: None,
            object_store: None,
            production: None,
            release_catalog: None,
            #[cfg(test)]
            fixture_auto_bind: false,
        }
    }
    /// Selects production mode with validated adapter connection settings.
    ///
    /// # Errors
    ///
    /// Returns [`StorageError::InvalidConfiguration`] when the supplied
    /// production settings are not valid.
    pub fn postgres_firebase_with_config(
        production: ProductionConfig,
    ) -> Result<Self, StorageError> {
        let production = production.validate()?;
        let mut config = Self::postgres_firebase();
        config.production = Some(production);
        Ok(config)
    }
    /// Replaces infrastructure with explicitly injected test adapters.
    #[cfg(test)]
    #[must_use]
    pub fn with_test_adapters(mut self, clock: Arc<dyn Clock>, entropy: Arc<dyn Entropy>) -> Self {
        self.clock = clock;
        self.entropy = entropy;
        self
    }
    /// Supplies non-production identity material for production-mode unit
    /// tests that exercise adapter-specific behavior.
    #[cfg(test)]
    #[must_use]
    pub(crate) fn with_test_identity(mut self) -> Self {
        self.invite_pepper = Zeroizing::new(vec![0x55; 32]);
        self.signing_key = SigningPrivateKey::from_bytes([7; 32]);
        self.signing_key_id = "production-test-key".to_owned();
        self
    }
    /// Replaces password hashing with an explicitly injected test engine.
    #[cfg(test)]
    #[must_use]
    pub fn with_password_engine(mut self, engine: Arc<dyn PasswordEngine>) -> Self {
        self.password_engine = engine;
        self
    }
    /// Replaces the local state and artifact adapters with explicit
    /// capability-oriented implementations.
    #[cfg(test)]
    #[must_use]
    pub fn with_adapters(
        mut self,
        repository: Arc<dyn Repository>,
        object_store: Arc<dyn ObjectStore>,
    ) -> Self {
        self.repository = Some(repository);
        self.object_store = Some(object_store);
        self
    }
    /// Sets the local upload URL prefix.
    #[must_use]
    pub fn with_upload_base_url(mut self, url: impl Into<String>) -> Self {
        self.upload_base_url = url.into();
        self
    }
}

fn valid_key_id(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= 128
        && value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'-' | b'_'))
}

#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub(crate) struct UserRecord {
    pub user_id: UserId,
    pub username: coop_cloud::Username,
    pub password_phc: String,
    pub character_id: CharacterId,
    pub disabled: bool,
}
#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub(crate) struct CharacterRecord {
    pub owner: UserId,
    pub state: CharacterCloudState,
    pub revision: Revision,
    /// Runtime world revision, independent from snapshot/save revision.
    pub world_revision: u64,
    pub active_snapshot: Option<SnapshotId>,
    /// Last committed snapshot in each registered ROM world. The active head
    /// remains `active_snapshot`; dormant heads preserve local campaigns for
    /// a future fenced travel handoff.
    #[serde(default)]
    pub world_heads: BTreeMap<RomWorldId, SnapshotId>,
    pub last_session_epoch: u32,
}

#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub(crate) struct RomHandoffStage {
    pub request: RomHandoffPrepareRequest,
    pub stage_id: SnapshotId,
    pub source_world_id: RomWorldId,
    pub destination_world_id: RomWorldId,
    pub arrival_portal_id: String,
    pub destination_save_sha256: Sha256Digest,
    pub expires_at: u64,
}

/// Durable replay fence for an aborted ROM handoff.  The exact prepare
/// request and stage identity remain reserved while its source snapshot is
/// still the character's active head.  A later prepare with the same
/// idempotency key can therefore never recreate an aborted stage after a
/// lost abort response.
#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub(crate) struct RomHandoffAbortTombstone {
    pub request: RomHandoffPrepareRequest,
    pub stage_id: SnapshotId,
    pub source_world_id: RomWorldId,
}

/// Server-owned paired stage. Immutable object keys are the two stage IDs;
/// neither source head changes while this record exists. A verifier may fill
/// each arrival slot independently, but only the paired commit may promote
/// both snapshots and the group zone in one repository transaction.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, Eq, PartialEq)]
#[serde(deny_unknown_fields)]
pub(crate) struct GroupRomHandoffStage {
    pub intent: GroupRomHandoffIntent,
    pub stage_ids: [SnapshotId; 2],
    /// Client intent keys are present for route-created stages. `None` keeps
    /// direct internal preparation fixtures compatible with the old shape.
    #[serde(default)]
    pub client_intent_keys: Option<[IdempotencyKey; 2]>,
    pub destination_save_sha256: [Sha256Digest; 2],
    pub arrival_challenges: [Sha256Digest; 2],
    pub verified_arrivals: [Option<VerifiedGroupRomArrival>; 2],
    pub expires_at: u64,
}

/// A durable rendezvous. Each slot is filled only by that member's own
/// authenticated request; neither caller may supply the companion's fence.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, Eq, PartialEq)]
#[serde(deny_unknown_fields)]
pub(crate) struct GroupRomHandoffProposal {
    pub group_id: GroupId,
    pub idempotency_key: IdempotencyKey,
    pub group_zone_revision: u64,
    pub source_zone: WorldZone,
    pub source_world_id: RomWorldId,
    pub destination_world_id: RomWorldId,
    pub portal_id: String,
    pub arrival_portal_id: String,
    pub catalog_sha256: Sha256Digest,
    pub descriptor_sha256: Sha256Digest,
    pub arrival_template_sha256: Sha256Digest,
    pub members: [Option<GroupRomHandoffSource>; 2],
    /// Each occupied member slot is paired with that member's durable key.
    #[serde(default)]
    pub client_intent_keys: [Option<IdempotencyKey>; 2],
    pub expires_at: u64,
}

impl GroupRomHandoffProposal {
    pub(crate) fn validate(&self) -> Result<(), StorageError> {
        if self.expires_at == 0
            || self.group_zone_revision > MAX_WORLD_REVISION
            || self.source_world_id == self.destination_world_id
            || self.portal_id.is_empty()
            || self.portal_id.len() > 64
            || self.arrival_portal_id.is_empty()
            || self.arrival_portal_id.len() > 64
            || !self.members.iter().any(Option::is_some)
            || self
                .members
                .iter()
                .zip(self.client_intent_keys)
                .any(|(member, key)| member.is_some() != key.is_some())
            || matches!(
                self.client_intent_keys,
                [Some(first), Some(second)] if first == second
            )
            || matches!(self.members, [Some(first), Some(second)] if first.fence.character_id >= second.fence.character_id)
        {
            return Err(StorageError::Transaction);
        }
        Ok(())
    }
}

#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, Eq, PartialEq)]
#[serde(deny_unknown_fields)]
pub(crate) struct VerifiedGroupRomArrival {
    pub stage_id: SnapshotId,
    pub destination_save_sha256: Sha256Digest,
    pub runtime: RuntimeLeaseFence,
    /// Digest of the independently authenticated arrival acknowledgment.
    pub acknowledgment_sha256: Sha256Digest,
}

/// Terminal result survives stage retirement. Aborts fence delayed prepare
/// replays for the exact source heads; commits replay the authoritative pair.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, Eq, PartialEq)]
#[serde(tag = "status", rename_all = "snake_case", deny_unknown_fields)]
pub(crate) enum GroupRomHandoffReceipt {
    Withdrawn {
        proposal: GroupRomHandoffProposal,
        resolved_at: u64,
    },
    Aborted {
        intent: GroupRomHandoffIntent,
        stage_ids: [SnapshotId; 2],
        #[serde(default)]
        client_intent_keys: Option<[IdempotencyKey; 2]>,
        resolved_at: u64,
    },
    Committed {
        intent: GroupRomHandoffIntent,
        snapshots: [SnapshotRecord; 2],
        destination_zone: WorldZone,
        group_zone_revision: u64,
        #[serde(default)]
        client_intent_keys: Option<[IdempotencyKey; 2]>,
        resolved_at: u64,
    },
}

impl GroupRomHandoffStage {
    pub(crate) fn validate(&self) -> Result<(), StorageError> {
        self.intent
            .validate()
            .map_err(|_| StorageError::Transaction)?;
        if self.stage_ids[0] == self.stage_ids[1]
            || self.arrival_challenges[0] == self.arrival_challenges[1]
            || self.expires_at == 0
            || self
                .verified_arrivals
                .iter()
                .enumerate()
                .any(|(index, arrival)| {
                    arrival.as_ref().is_some_and(|arrival| {
                        let fence = self.intent.members[index].fence;
                        let request = GroupRomHandoffArrivalRequest {
                            api_version: coop_cloud::ApiVersion::V1,
                            group_id: self.intent.group_id,
                            fence,
                            idempotency_key: self.intent.idempotency_key,
                            stage_id: arrival.stage_id,
                            destination_save_sha256: arrival.destination_save_sha256,
                            destination_build: arrival.runtime.build.clone(),
                            acknowledgment_mac: arrival.acknowledgment_sha256,
                        };
                        arrival.stage_id != self.stage_ids[index]
                            || arrival.destination_save_sha256
                                != self.destination_save_sha256[index]
                            || arrival.runtime.session
                                != StableRuntimeSession::from_lease_fence(&fence)
                            || request.expected_mac(self.arrival_challenges[index])
                                != arrival.acknowledgment_sha256
                    })
                })
        {
            return Err(StorageError::Transaction);
        }
        if self
            .client_intent_keys
            .is_some_and(|keys| keys[0] == keys[1])
        {
            return Err(StorageError::Transaction);
        }
        Ok(())
    }
}

impl GroupRomHandoffReceipt {
    pub(crate) fn validate(&self) -> Result<(), StorageError> {
        match self {
            Self::Withdrawn {
                proposal,
                resolved_at,
            } => {
                proposal.validate()?;
                if *resolved_at == 0 {
                    return Err(StorageError::Transaction);
                }
            }
            Self::Aborted {
                intent,
                stage_ids,
                client_intent_keys,
                resolved_at,
            } => {
                intent.validate().map_err(|_| StorageError::Transaction)?;
                if stage_ids[0] == stage_ids[1]
                    || *resolved_at == 0
                    || client_intent_keys.is_some_and(|keys| keys[0] == keys[1])
                {
                    return Err(StorageError::Transaction);
                }
            }
            Self::Committed {
                intent,
                snapshots,
                group_zone_revision,
                client_intent_keys,
                resolved_at,
                ..
            } => {
                intent.validate().map_err(|_| StorageError::Transaction)?;
                if snapshots[0].snapshot_id == snapshots[1].snapshot_id
                    || intent.group_zone_revision.checked_add(1) != Some(*group_zone_revision)
                    || *group_zone_revision > MAX_WORLD_REVISION
                    || *resolved_at == 0
                    || client_intent_keys.is_some_and(|keys| keys[0] == keys[1])
                    || snapshots.iter().enumerate().any(|(index, snapshot)| {
                        snapshot.character_id != intent.members[index].fence.character_id
                            || snapshot.rom_world_id != intent.destination_world_id
                            || snapshot.parent_revision
                                != intent.members[index].fence.current_revision
                            || intent.members[index].fence.current_revision.next().ok()
                                != Some(snapshot.revision)
                    })
                {
                    return Err(StorageError::Transaction);
                }
            }
        }
        Ok(())
    }

    pub(crate) fn resolved_at(&self) -> u64 {
        match self {
            Self::Withdrawn { resolved_at, .. }
            | Self::Aborted { resolved_at, .. }
            | Self::Committed { resolved_at, .. } => *resolved_at,
        }
    }

    pub(crate) fn client_intent_keys(&self) -> [Option<IdempotencyKey>; 2] {
        match self {
            Self::Withdrawn { proposal, .. } => proposal.client_intent_keys,
            Self::Aborted {
                client_intent_keys, ..
            }
            | Self::Committed {
                client_intent_keys, ..
            } => client_intent_keys
                .as_ref()
                .map(|keys| [Some(keys[0]), Some(keys[1])])
                .unwrap_or([None, None]),
        }
    }
}

/// Remove terminal replay tombstones outside the bounded recovery window.
/// Callers hold the repository write transaction while invoking this helper.
pub(crate) fn prune_group_rom_handoff_receipts(state: &mut State, now: u64) {
    let floor = now
        .max(state.group_rom_handoff_receipt_high_water)
        .saturating_sub(GROUP_ROM_HANDOFF_RECEIPT_RETENTION_MS);
    state
        .group_rom_handoff_receipts
        .retain(|_, receipt| receipt.resolved_at() > floor);
}

pub(crate) fn ensure_group_rom_handoff_receipt_capacity(
    state: &State,
    key: (GroupId, IdempotencyKey),
    now: u64,
) -> Result<(), StorageError> {
    let floor = now
        .max(state.group_rom_handoff_receipt_high_water)
        .saturating_sub(GROUP_ROM_HANDOFF_RECEIPT_RETENTION_MS);
    let retained = state
        .group_rom_handoff_receipts
        .values()
        .filter(|receipt| receipt.resolved_at() > floor)
        .count();
    let group_reserved = state
        .group_rom_handoff_receipt_reservations
        .contains_key(&key.0);
    let other_reservations = state
        .group_rom_handoff_receipt_reservations
        .len()
        .saturating_sub(if group_reserved { 1 } else { 0 });
    let needed_receipt = if state.group_rom_handoff_receipts.contains_key(&key) {
        0
    } else {
        1
    };
    if retained
        .saturating_add(other_reservations)
        .saturating_add(needed_receipt)
        > MAX_GROUP_ROM_HANDOFF_RECEIPTS
    {
        return Err(StorageError::Busy);
    }
    Ok(())
}

pub(crate) fn reserve_group_rom_handoff_receipt(
    state: &mut State,
    key: (GroupId, IdempotencyKey),
    now: u64,
) -> Result<(), StorageError> {
    if state
        .group_rom_handoff_receipt_reservations
        .contains_key(&key.0)
    {
        return Ok(());
    }
    ensure_group_rom_handoff_receipt_capacity(state, key, now)?;
    state
        .group_rom_handoff_receipt_reservations
        .insert(key.0, ());
    Ok(())
}

/// Persists one terminal receipt while keeping the replay cache bounded. Only
/// receipts outside the recovery window are removed. If all retained receipts
/// are still live, the caller must retry after the window advances; evicting a
/// live tombstone would let a delayed client intent become a new proposal.
pub(crate) fn record_group_rom_handoff_receipt(
    state: &mut State,
    key: (GroupId, IdempotencyKey),
    receipt: GroupRomHandoffReceipt,
    now: u64,
) -> Result<(), StorageError> {
    let effective_now = now.max(state.group_rom_handoff_receipt_high_water);
    prune_group_rom_handoff_receipts(state, effective_now);
    ensure_group_rom_handoff_receipt_capacity(state, key, effective_now)?;
    state.group_rom_handoff_receipt_reservations.remove(&key.0);
    state.group_rom_handoff_receipt_high_water = state
        .group_rom_handoff_receipt_high_water
        .max(receipt.resolved_at())
        .max(now);
    state.group_rom_handoff_receipts.insert(key, receipt);
    Ok(())
}

fn deserialize_bounded_group_handoff_map<'de, D, K, V>(
    deserializer: D,
    limit: usize,
    validate: fn(&K, &V) -> Result<(), StorageError>,
) -> Result<HashMap<K, V>, D::Error>
where
    D: serde::Deserializer<'de>,
    K: serde::Deserialize<'de> + Eq + std::hash::Hash,
    V: serde::Deserialize<'de>,
{
    struct BoundedMap<K, V> {
        limit: usize,
        validate: fn(&K, &V) -> Result<(), StorageError>,
        marker: std::marker::PhantomData<K>,
    }
    impl<'de, K, V> Visitor<'de> for BoundedMap<K, V>
    where
        K: serde::Deserialize<'de> + Eq + std::hash::Hash,
        V: serde::Deserialize<'de>,
    {
        type Value = HashMap<K, V>;

        fn expecting(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
            write!(formatter, "at most {} valid handoff records", self.limit)
        }

        fn visit_map<A>(self, mut map: A) -> Result<Self::Value, A::Error>
        where
            A: MapAccess<'de>,
        {
            if map.size_hint().is_some_and(|size| size > self.limit) {
                return Err(serde::de::Error::custom("handoff map exceeds limit"));
            }
            let mut records = HashMap::new();
            while let Some((key, value)) = map.next_entry::<K, V>()? {
                if records.len() >= self.limit
                    || (self.validate)(&key, &value).is_err()
                    || records.insert(key, value).is_some()
                {
                    return Err(serde::de::Error::custom("invalid handoff record"));
                }
            }
            Ok(records)
        }
    }
    deserializer.deserialize_map(BoundedMap {
        limit,
        validate,
        marker: std::marker::PhantomData,
    })
}

fn deserialize_group_rom_handoff_stages<'de, D>(
    deserializer: D,
) -> Result<HashMap<GroupId, GroupRomHandoffStage>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    deserialize_bounded_group_handoff_map(
        deserializer,
        MAX_GROUP_ROM_HANDOFF_STAGES,
        |group_id, stage| {
            stage.validate()?;
            if stage.intent.group_id != *group_id {
                return Err(StorageError::Transaction);
            }
            Ok(())
        },
    )
}

fn deserialize_group_rom_handoff_proposals<'de, D>(
    deserializer: D,
) -> Result<HashMap<GroupId, GroupRomHandoffProposal>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    deserialize_bounded_group_handoff_map(
        deserializer,
        MAX_GROUP_ROM_HANDOFF_STAGES,
        |group_id, proposal| {
            proposal.validate()?;
            if proposal.group_id != *group_id {
                return Err(StorageError::Transaction);
            }
            Ok(())
        },
    )
}

fn deserialize_group_rom_handoff_receipts<'de, D>(
    deserializer: D,
) -> Result<HashMap<(GroupId, IdempotencyKey), GroupRomHandoffReceipt>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    deserialize_bounded_group_handoff_map(
        deserializer,
        MAX_GROUP_ROM_HANDOFF_RECEIPTS,
        |(group_id, key), receipt| {
            receipt.validate()?;
            let intent = match receipt {
                GroupRomHandoffReceipt::Withdrawn { proposal, .. } => {
                    if proposal.group_id != *group_id || proposal.idempotency_key != *key {
                        return Err(StorageError::Transaction);
                    }
                    return Ok(());
                }
                GroupRomHandoffReceipt::Aborted { intent, .. }
                | GroupRomHandoffReceipt::Committed { intent, .. } => intent,
            };
            if intent.group_id != *group_id || intent.idempotency_key != *key {
                return Err(StorageError::Transaction);
            }
            Ok(())
        },
    )
}

fn deserialize_group_rom_handoff_reservations<'de, D>(
    deserializer: D,
) -> Result<HashMap<GroupId, ()>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    deserialize_bounded_group_handoff_map(
        deserializer,
        MAX_GROUP_ROM_HANDOFF_STAGES,
        |_group_id, _unit| Ok(()),
    )
}

#[derive(serde::Serialize, serde::Deserialize, Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum GroupStatus {
    Active,
    Closed,
}

#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub(crate) struct GroupRecord {
    pub group: Group,
    pub zone: WorldZone,
    pub status: GroupStatus,
    #[serde(default)]
    pub zone_revision: u64,
}

#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub(crate) struct GroupTravelProposalRecord {
    pub view: GroupTravelProposalView,
    pub retain_until: Option<u64>,
}

#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub(crate) struct GroupTravelProposalIdempotencyRecord {
    pub fingerprint: [u8; 32],
    pub response: GroupTravelProposalView,
    pub expires_at: u64,
    pub lifecycle: bool,
}

#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub(crate) struct GroupInvitationRecord {
    pub invitation_id: GroupInvitationId,
    pub inviter: CharacterId,
    pub invitee: CharacterId,
    pub expires_at: u64,
    pub consumed: bool,
}

#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub(crate) enum GroupIdempotencyResponse {
    Online(coop_cloud::OnlineActionResponse),
    Invitation(coop_cloud::CreateGroupInvitationResponse),
    Accept(coop_cloud::AcceptGroupInvitationResponse),
    Travel(coop_cloud::GroupTravelResponse),
}

#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub(crate) struct GroupIdempotencyRecord {
    pub fingerprint: [u8; 32],
    pub response: GroupIdempotencyResponse,
    pub expires_at: u64,
}
#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub(crate) struct AccessRecord {
    pub user_id: UserId,
    pub character_id: CharacterId,
    pub family_id: RefreshFamilyId,
    pub expires_at: u64,
    pub revoked: bool,
}
#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub(crate) struct RefreshRecord {
    pub user_id: UserId,
    pub character_id: CharacterId,
    pub family_id: RefreshFamilyId,
    pub generation: u32,
    pub expires_at: u64,
    pub consumed: bool,
}
#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub(crate) struct FamilyRecord {
    pub user_id: UserId,
    pub character_id: CharacterId,
    pub expires_at: u64,
    pub revoked: bool,
}
#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub(crate) struct LeaseRecord {
    pub contract: LeaseContract,
    pub grace_until: u64,
    pub released: bool,
    pub reconnect: Option<(IdempotencyKey, coop_cloud::LeaseFence, LeaseContract)>,
    pub release_keys: Vec<(IdempotencyKey, coop_cloud::LeaseFence)>,
    #[serde(default)]
    pub runtime_binding: Option<RuntimeWorldBinding>,
}

#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, Eq, PartialEq)]
pub(crate) struct RuntimeWorldBinding {
    pub world_id: RomWorldId,
    pub build: RuntimeBuildIdentity,
    pub session: StableRuntimeSession,
}
#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub(crate) struct PreparedSnapshot {
    pub request: SnapshotPrepareRequest,
    pub upload_targets: Vec<UploadTarget>,
    pub expires_at: u64,
}
#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub(crate) struct RestoreStage {
    pub request: SnapshotRestoreRequest,
    pub snapshot_id: SnapshotId,
    pub expires_at: u64,
    /// Declared bytes reserved by this restore while object copying is in
    /// progress. The reservation is counted against the character quota.
    pub storage_bytes: u64,
    /// Owned copies and verified-absent destination keys reserved for cleanup.
    /// Recovery seals absent keys before retiring the stage so a delayed
    /// publisher cannot recreate abandoned copies.
    pub created_objects: Vec<String>,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, Copy)]
pub(crate) struct UploadObjectRecord {
    /// Capability fingerprint that created this object.
    pub fingerprint: [u8; 32],
    /// Set while cleanup has claimed the object. Finalization must not adopt
    /// a claimed object, and failed deletion leaves the claim retryable.
    pub cleanup_claimed: bool,
}
#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub(crate) struct TicketRecord {
    pub actor: UserId,
    pub character_id: CharacterId,
    pub snapshot_id: SnapshotId,
    pub artifact: coop_cloud::ArtifactIdentity,
    pub method: coop_cloud::UploadMethod,
    pub expected: SnapshotFile,
    pub expires_at: u64,
    pub used: bool,
}

/// A one-use realtime capability.  The raw ticket is never retained: only
/// the domain-separated fingerprint is used as the repository key.
#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub(crate) struct RealtimeTicketRecord {
    pub user_id: UserId,
    pub character_id: CharacterId,
    pub session: StableRuntimeSession,
    pub runtime: RuntimeLeaseFence,
    pub expires_at: u64,
}

#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub(crate) struct AcquireRecord {
    pub character_id: CharacterId,
    pub client_instance_id: ClientInstanceId,
    pub contract: LeaseContract,
    pub expires_at: u64,
}

#[derive(serde::Serialize, serde::Deserialize, Clone, Default)]
pub struct State {
    pub(crate) users_by_name: HashMap<String, UserRecord>,
    pub(crate) users_by_id: HashMap<UserId, UserRecord>,
    pub(crate) characters: HashMap<CharacterId, CharacterRecord>,
    pub(crate) invitations: HashMap<[u8; 32], bool>,
    #[serde(default)]
    pub(crate) invitation_issuers: HashMap<[u8; 32], UserId>,
    #[serde(default)]
    pub(crate) invitation_expires_at: HashMap<[u8; 32], u64>,
    pub(crate) access: HashMap<[u8; 32], AccessRecord>,
    pub(crate) refresh: HashMap<[u8; 32], RefreshRecord>,
    pub(crate) families: HashMap<RefreshFamilyId, FamilyRecord>,
    pub(crate) leases: HashMap<CharacterId, LeaseRecord>,
    pub(crate) acquire_history: HashMap<IdempotencyKey, AcquireRecord>,
    pub(crate) prepared: HashMap<SnapshotId, PreparedSnapshot>,
    pub(crate) prepare_ops: HashMap<(CharacterId, IdempotencyKey), SnapshotId>,
    pub(crate) snapshots: HashMap<SnapshotId, SnapshotRecord>,
    pub(crate) snapshot_by_revision: HashMap<(CharacterId, Revision), SnapshotId>,
    pub(crate) finalize_ops:
        HashMap<(CharacterId, IdempotencyKey), (SnapshotFinalizeRequest, SnapshotRecord)>,
    pub(crate) restore_ops:
        HashMap<(CharacterId, IdempotencyKey), (SnapshotRestoreRequest, SnapshotRecord)>,
    pub(crate) restore_staging: HashMap<CharacterId, RestoreStage>,
    #[serde(default)]
    pub(crate) rom_handoff_staging: HashMap<CharacterId, RomHandoffStage>,
    #[serde(default)]
    pub(crate) rom_handoff_commits:
        HashMap<(CharacterId, IdempotencyKey), (RomHandoffCommitRequest, SnapshotRecord)>,
    /// Aborted handoff intents keyed by their exact source character and
    /// idempotency key.  Entries are retained until that source head advances
    /// and are bounded per character.
    #[serde(default)]
    pub(crate) rom_handoff_aborts: HashMap<(CharacterId, IdempotencyKey), RomHandoffAbortTombstone>,
    /// Paired cross-ROM stages and terminal outcomes are separate from the
    /// existing solo path; endpoints remain unavailable until atomic commit.
    #[serde(default, deserialize_with = "deserialize_group_rom_handoff_stages")]
    pub(crate) group_rom_handoff_stages: HashMap<GroupId, GroupRomHandoffStage>,
    #[serde(default, deserialize_with = "deserialize_group_rom_handoff_proposals")]
    pub(crate) group_rom_handoff_proposals: HashMap<GroupId, GroupRomHandoffProposal>,
    #[serde(default, deserialize_with = "deserialize_group_rom_handoff_receipts")]
    pub(crate) group_rom_handoff_receipts:
        HashMap<(GroupId, IdempotencyKey), GroupRomHandoffReceipt>,
    /// One reserved terminal-receipt slot per live proposal or stage. The
    /// reservation is consumed atomically when its terminal receipt lands.
    #[serde(
        default,
        deserialize_with = "deserialize_group_rom_handoff_reservations"
    )]
    pub(crate) group_rom_handoff_receipt_reservations: HashMap<GroupId, ()>,
    /// Monotonic server-time high-water for terminal handoff tombstones.
    /// It prevents a restored clock from extending an already-expired replay
    /// window while remaining a single bounded scalar.
    #[serde(default)]
    pub(crate) group_rom_handoff_receipt_high_water: u64,
    /// Snapshots removed from history in the same transaction as a new handoff
    /// head, awaiting idempotent object-store retirement after that commit.
    #[serde(default)]
    pub(crate) retiring_snapshots: HashMap<SnapshotId, SnapshotRecord>,
    pub(crate) retired_snapshots: HashSet<SnapshotId>,
    pub(crate) tickets: HashMap<[u8; 32], TicketRecord>,
    pub(crate) realtime_tickets: HashMap<[u8; 32], RealtimeTicketRecord>,
    /// Refresh-family binding for realtime capabilities.  This is kept in a
    /// separate defaulted map so older persisted ticket records remain
    /// readable but fail closed when redeemed until replaced.
    #[serde(default)]
    pub(crate) realtime_ticket_families: HashMap<[u8; 32], RefreshFamilyId>,
    /// Reverse lookup used to replace a prior capability for one runtime
    /// session atomically.  Values are fingerprints, never raw secrets.
    pub(crate) realtime_by_runtime: HashMap<(UserId, StableRuntimeSession), [u8; 32]>,
    /// Repository-side ownership records close the check-then-delete race
    /// between failed uploads and concurrent finalization.
    pub(crate) upload_objects: HashMap<String, UploadObjectRecord>,
    pub(crate) groups: HashMap<GroupId, GroupRecord>,
    pub(crate) active_group_by_member: HashMap<CharacterId, GroupId>,
    pub(crate) group_invitations: HashMap<GroupInvitationId, GroupInvitationRecord>,
    pub(crate) group_idempotency:
        HashMap<(CharacterId, String, IdempotencyKey), GroupIdempotencyRecord>,
    #[serde(default)]
    pub(crate) group_travel_proposals: HashMap<GroupTravelProposalId, GroupTravelProposalRecord>,
    #[serde(default)]
    pub(crate) live_group_travel_by_group: HashMap<GroupId, GroupTravelProposalId>,
    #[serde(default)]
    pub(crate) live_group_travel_by_member: HashMap<CharacterId, GroupTravelProposalId>,
    #[serde(default)]
    pub(crate) group_travel_proposal_idempotency:
        HashMap<(CharacterId, String, IdempotencyKey), GroupTravelProposalIdempotencyRecord>,
}

impl State {
    /// All ordinary runtime and group mutations are fenced while either
    /// member's source save is staged for a paired ROM switch.
    pub(crate) fn paired_handoff_for_member(&self, character_id: CharacterId) -> bool {
        self.active_group_by_member
            .get(&character_id)
            .is_some_and(|group_id| self.group_rom_handoff_stages.contains_key(group_id))
    }
}
#[derive(Clone)]
pub(crate) struct Store {
    pub(crate) repository: Arc<dyn Repository>,
    pub config: Arc<Phase2Config>,
    pub(crate) clock_floor: Arc<AtomicU64>,
    /// Process-local wall-clock anchor used by ephemeral presence. Persisted
    /// Unix timestamps continue to use `clock`/`now`; presence deadlines use
    /// elapsed monotonic time so an NTP step cannot evict every socket.
    pub(crate) monotonic_wall_anchor: Arc<MonotonicWallAnchor>,
    pub(crate) objects: Arc<dyn ObjectStore>,
    /// Serializes transitions that need a repository snapshot and an
    /// ephemeral runtime reconciliation. Presence owns no repository lock,
    /// so the order is always gate -> repository -> presence.
    pub(crate) runtime_transition_gate: Arc<std::sync::Mutex<()>>,
    account_inflight: Arc<std::sync::Mutex<HashSet<String>>>,
    heartbeat_last: Arc<std::sync::Mutex<HashMap<CharacterId, Instant>>>,
}

#[derive(Debug)]
pub(crate) struct MonotonicWallAnchor {
    wall_ms: u64,
    started: Instant,
}

impl MonotonicWallAnchor {
    fn new(wall_ms: u64) -> Self {
        Self {
            wall_ms,
            started: Instant::now(),
        }
    }

    fn now_ms(&self) -> u64 {
        self.wall_ms.saturating_add(
            self.started
                .elapsed()
                .as_millis()
                .try_into()
                .unwrap_or(u64::MAX),
        )
    }
}

impl Store {
    pub(crate) fn lock_runtime_transition_gate(&self) -> std::sync::MutexGuard<'_, ()> {
        match self.runtime_transition_gate.lock() {
            Ok(guard) => guard,
            Err(poisoned) => {
                let guard = poisoned.into_inner();
                self.runtime_transition_gate.clear_poison();
                guard
            }
        }
    }

    pub fn new(config: Phase2Config) -> Result<Self, StorageError> {
        if config.mode == StorageMode::PostgresFirebase
            && (config.production.is_none()
                || config.repository.is_none()
                || config.object_store.is_none())
        {
            return Err(StorageError::ProductionUnavailable);
        }
        let upload_url = url::Url::parse(&config.upload_base_url)
            .map_err(|_| StorageError::InvalidConfiguration)?;
        let loopback = match upload_url.host() {
            Some(url::Host::Ipv4(address)) => address == std::net::Ipv4Addr::LOCALHOST,
            Some(url::Host::Ipv6(address)) => address == std::net::Ipv6Addr::LOCALHOST,
            None | Some(url::Host::Domain(_)) => false,
        };
        let valid_origin = match config.mode {
            StorageMode::Phase2Local => upload_url.scheme() == "http" && loopback,
            StorageMode::PostgresFirebase => {
                upload_url.scheme() == "https" && upload_url.host_str().is_some()
            }
        };
        if !valid_origin
            || config.invite_pepper.len() < 16
            || !valid_key_id(&config.signing_key_id)
            || !upload_url.username().is_empty()
            || upload_url.password().is_some()
            || upload_url.query().is_some()
            || upload_url.fragment().is_some()
            || (!upload_url.path().is_empty() && upload_url.path() != "/")
        {
            return Err(StorageError::InvalidConfiguration);
        }
        let repository: Arc<dyn Repository> = config
            .repository
            .clone()
            .unwrap_or_else(|| Arc::new(InMemoryRepository::new()));
        let object_store: Arc<dyn ObjectStore> = config
            .object_store
            .clone()
            .unwrap_or_else(|| Arc::new(InMemoryObjectStore::new()));
        let monotonic_wall_anchor = Arc::new(MonotonicWallAnchor::new(config.clock.now_ms()));
        Ok(Self {
            repository,
            config: Arc::new(config),
            clock_floor: Arc::new(AtomicU64::new(0)),
            monotonic_wall_anchor,
            objects: object_store,
            runtime_transition_gate: Arc::new(std::sync::Mutex::new(())),
            account_inflight: Arc::new(std::sync::Mutex::new(HashSet::new())),
            heartbeat_last: Arc::new(std::sync::Mutex::new(HashMap::new())),
        })
    }

    pub(crate) fn admit_heartbeat(&self, character_id: CharacterId) -> Result<(), StorageError> {
        if self.config.mode != StorageMode::PostgresFirebase {
            return Ok(());
        }
        let now = Instant::now();
        let mut last = match self.heartbeat_last.lock() {
            Ok(guard) => guard,
            Err(poisoned) => {
                let mut guard = poisoned.into_inner();
                guard.clear();
                self.heartbeat_last.clear_poison();
                guard
            }
        };
        if last
            .get(&character_id)
            .is_some_and(|at| now.duration_since(*at) < Duration::from_secs(2))
        {
            return Err(StorageError::Busy);
        }
        last.insert(character_id, now);
        if last.len() > MAX_ACCESS_RECORDS_GLOBAL {
            last.retain(|_, at| now.duration_since(*at) < Duration::from_secs(2));
        }
        Ok(())
    }
    pub(crate) fn now(&self) -> u64 {
        let observed = self.config.clock.now_ms();
        let mut previous = self.clock_floor.load(Ordering::Acquire);
        loop {
            if observed <= previous {
                return previous;
            }
            match self.clock_floor.compare_exchange_weak(
                previous,
                observed,
                Ordering::AcqRel,
                Ordering::Acquire,
            ) {
                Ok(_) => return observed,
                Err(current) => previous = current,
            }
        }
    }

    /// Returns the process-local time used by ephemeral presence state.
    /// Production presence is anchored once to the wall clock and advances
    /// with `Instant`; local mode keeps its deterministic/test clock.
    pub(crate) fn presence_now(&self) -> u64 {
        if self.config.mode == StorageMode::PostgresFirebase {
            self.monotonic_wall_anchor.now_ms()
        } else {
            self.now()
        }
    }

    /// Executes a short read-only repository operation under the adapter's
    /// transaction boundary. Callers must copy all data needed before doing
    /// object-store or other blocking work.
    pub(crate) fn read_transaction<T, E, F>(&self, operation: F) -> Result<T, E>
    where
        E: From<StorageError>,
        F: FnOnce(&State) -> Result<T, E>,
    {
        let mut operation = Some(operation);
        let mut result = None;
        let mut failure = None;
        let mut callback = |state: &State| {
            let Some(operation) = operation.take() else {
                return Err(StorageError::Transaction);
            };
            match operation(state) {
                Ok(value) => {
                    result = Some(value);
                    Ok(())
                }
                Err(error) => {
                    failure = Some(error);
                    Err(StorageError::Transaction)
                }
            }
        };
        self.repository
            .read_transaction(&mut callback)
            .map_err(|error| failure.take().unwrap_or_else(|| E::from(error)))?;
        result.ok_or_else(|| E::from(StorageError::Transaction))
    }

    /// Executes a short atomic repository transition. Object-store calls must
    /// happen outside this callback; this is the semantic write boundary used
    /// by snapshot/session transitions.
    pub(crate) fn write_transaction<T, E, F>(&self, operation: F) -> Result<T, E>
    where
        E: From<StorageError>,
        F: FnOnce(&mut State) -> Result<T, E>,
    {
        let mut operation = Some(operation);
        let mut result = None;
        let mut failure = None;
        let mut callback = |state: &mut State| {
            let Some(operation) = operation.take() else {
                return Err(StorageError::Transaction);
            };
            match operation(state) {
                Ok(value) => {
                    result = Some(value);
                    Ok(())
                }
                Err(error) => {
                    failure = Some(error);
                    Err(StorageError::Transaction)
                }
            }
        };
        self.repository
            .write_transaction(&mut callback)
            .map_err(|error| {
                if matches!(
                    error,
                    StorageError::Persistence | StorageError::StateTooLarge | StorageError::Busy
                ) {
                    E::from(error)
                } else {
                    failure.take().unwrap_or_else(|| E::from(error))
                }
            })?;
        result.ok_or_else(|| E::from(StorageError::Transaction))
    }

    #[cfg(test)]
    pub(crate) fn inspect_state<T, F>(&self, operation: F) -> Result<T, StorageError>
    where
        F: FnOnce(&State) -> T,
    {
        self.read_transaction(|state| Ok(operation(state)))
    }

    pub(crate) fn try_account_admission(
        &self,
        username: &str,
    ) -> Result<Option<AccountAdmission>, StorageError> {
        let mut active = self
            .account_inflight
            .lock()
            .map_err(|_| StorageError::Lock)?;
        if !active.insert(username.to_owned()) {
            return Ok(None);
        }
        Ok(Some(AccountAdmission {
            active: self.account_inflight.clone(),
            username: username.to_owned(),
        }))
    }
    pub(crate) fn invitation_fingerprint(&self, code: &str) -> [u8; 32] {
        let mut mac = hmac::Hmac::<Sha256>::new_from_slice(&self.config.invite_pepper)
            .expect("HMAC accepts every key");
        mac.update(code.as_bytes());
        mac.finalize().into_bytes().into()
    }
    pub(crate) fn token_fingerprint(token: &str) -> [u8; 32] {
        Sha256::digest(token.as_bytes()).into()
    }
    pub(crate) fn random_token(&self) -> Result<String, StorageError> {
        let mut bytes = Zeroizing::new([0_u8; 32]);
        self.config.entropy.fill(&mut bytes[..])?;
        Ok(URL_SAFE_NO_PAD.encode(bytes.as_slice()))
    }
    pub(crate) fn random_challenge(&self) -> Result<Sha256Digest, StorageError> {
        let mut bytes = [0_u8; 32];
        self.config.entropy.fill(&mut bytes)?;
        Ok(Sha256Digest::from_bytes(bytes))
    }
    pub(crate) fn random_uuid(&self) -> Result<Uuid, StorageError> {
        let mut bytes = [0_u8; 16];
        self.config.entropy.fill(&mut bytes)?;
        bytes[6] = (bytes[6] & 0x0f) | 0x40;
        bytes[8] = (bytes[8] & 0x3f) | 0x80;
        Ok(Uuid::from_bytes(bytes))
    }
    pub(crate) fn user_id(&self) -> Result<UserId, StorageError> {
        UserId::new(self.random_uuid()?).map_err(|_| StorageError::Entropy)
    }
    pub(crate) fn character_id(&self) -> Result<CharacterId, StorageError> {
        CharacterId::new(self.random_uuid()?).map_err(|_| StorageError::Entropy)
    }
    pub(crate) fn family_id(&self) -> Result<RefreshFamilyId, StorageError> {
        RefreshFamilyId::new(self.random_uuid()?).map_err(|_| StorageError::Entropy)
    }
    pub(crate) fn session_id(&self) -> Result<SessionId, StorageError> {
        SessionId::new(self.random_uuid()?).map_err(|_| StorageError::Entropy)
    }
    pub(crate) fn snapshot_id(&self) -> Result<SnapshotId, StorageError> {
        SnapshotId::new(self.random_uuid()?).map_err(|_| StorageError::Entropy)
    }
    pub(crate) fn initial_state(
        character_id: CharacterId,
    ) -> Result<CharacterCloudState, StorageError> {
        let progress = RegionalProgress::new(RegionId::Hoenn, 0, 0, vec![], vec![])
            .map_err(|_| StorageError::Entropy)?;
        CharacterCloudState::new(
            character_id,
            WorldZone::new(RegionId::Hoenn, "LITTLEROOT_TOWN", 1)
                .map_err(|_| StorageError::Entropy)?,
            vec![progress],
        )
        .map_err(|_| StorageError::Entropy)
    }
    pub(crate) fn object_key(
        character: CharacterId,
        snapshot: SnapshotId,
        artifact: coop_cloud::ArtifactIdentity,
    ) -> String {
        format!(
            "characters/{character}/snapshots/{snapshot}/{}",
            artifact.as_str()
        )
    }
    pub(crate) fn unix_timestamp(value: u64) -> Result<UnixTimestampMillis, StorageError> {
        if value == 0 {
            return Err(StorageError::Clock);
        }
        Ok(UnixTimestampMillis::new(value))
    }
}

pub(crate) struct AccountAdmission {
    active: Arc<std::sync::Mutex<HashSet<String>>>,
    username: String,
}

impl Drop for AccountAdmission {
    fn drop(&mut self) {
        if let Ok(mut active) = self.active.lock() {
            active.remove(&self.username);
        }
    }
}
pub(crate) fn is_artifact_size_allowed(artifact: coop_cloud::ArtifactIdentity, size: u64) -> bool {
    match artifact {
        coop_cloud::ArtifactIdentity::CharacterSav => {
            size == coop_save::FLASH_IMAGE_SIZE as u64 || size == MAX_CHARACTER_SAV
        }
        coop_cloud::ArtifactIdentity::PendingCommits => size <= MAX_PENDING_COMMITS,
        coop_cloud::ArtifactIdentity::ResumeSs1 => size > 0 && size <= MAX_RESUME_SS1,
    }
}
pub(crate) fn commit_id_allowed(commit: Option<CommitId>) -> bool {
    commit.is_none()
}

#[cfg(test)]
mod group_rom_handoff_state_tests {
    use super::*;
    use coop_cloud::{ApiVersion, GroupRomHandoffSource, LeaseFence, SessionEpoch, SnapshotFence};
    use uuid::Uuid;

    fn uuid_id<T>(number: u128, constructor: fn(Uuid) -> Result<T, coop_cloud::IdError>) -> T {
        constructor(Uuid::from_u128(number)).unwrap()
    }

    fn intent() -> GroupRomHandoffIntent {
        let source = |number: u128| GroupRomHandoffSource {
            fence: LeaseFence::new(
                uuid_id(number + 10, SessionId::new),
                uuid_id(number, CharacterId::new),
                Revision::new(1),
                SessionEpoch::new(1).unwrap(),
                uuid_id(number + 20, ClientInstanceId::new),
            ),
            source_snapshot_id: uuid_id(number + 30, SnapshotId::new),
        };
        GroupRomHandoffIntent {
            api_version: ApiVersion::V1,
            group_id: uuid_id(100, GroupId::new),
            group_zone_revision: 1,
            source_zone: WorldZone::new(RegionId::Hoenn, "LILYCOVE_CITY_HARBOR", 1).unwrap(),
            source_world_id: RomWorldId::new(1).unwrap(),
            destination_world_id: RomWorldId::new(2).unwrap(),
            portal_id: "to_cormoria".into(),
            arrival_portal_id: "rivetshore_harbor".into(),
            catalog_sha256: Sha256Digest::of_bytes(b"catalog"),
            descriptor_sha256: Sha256Digest::of_bytes(b"descriptor"),
            arrival_template_sha256: Sha256Digest::of_bytes(b"arrival"),
            members: [source(1), source(2)],
            idempotency_key: uuid_id(101, IdempotencyKey::new),
        }
    }

    fn stage() -> GroupRomHandoffStage {
        GroupRomHandoffStage {
            intent: intent(),
            stage_ids: [uuid_id(200, SnapshotId::new), uuid_id(201, SnapshotId::new)],
            client_intent_keys: None,
            destination_save_sha256: [
                Sha256Digest::of_bytes(b"member one"),
                Sha256Digest::of_bytes(b"member two"),
            ],
            arrival_challenges: [
                Sha256Digest::of_bytes(b"challenge one"),
                Sha256Digest::of_bytes(b"challenge two"),
            ],
            verified_arrivals: [None, None],
            expires_at: 1_700_000_300_000,
        }
    }

    fn proposal() -> GroupRomHandoffProposal {
        let intent = intent();
        GroupRomHandoffProposal {
            group_id: intent.group_id,
            idempotency_key: intent.idempotency_key,
            group_zone_revision: intent.group_zone_revision,
            source_zone: intent.source_zone,
            source_world_id: intent.source_world_id,
            destination_world_id: intent.destination_world_id,
            portal_id: intent.portal_id,
            arrival_portal_id: intent.arrival_portal_id,
            catalog_sha256: intent.catalog_sha256,
            descriptor_sha256: intent.descriptor_sha256,
            arrival_template_sha256: intent.arrival_template_sha256,
            members: [Some(intent.members[0]), None],
            client_intent_keys: [Some(uuid_id(500, IdempotencyKey::new)), None],
            expires_at: 1_700_000_300_000,
        }
    }

    #[test]
    fn paired_proposal_survives_restart_and_rejects_bad_key_or_member_order() {
        let proposal = proposal();
        let mut state = State::default();
        state
            .group_rom_handoff_proposals
            .insert(proposal.group_id, proposal.clone());
        assert_eq!(
            decode(&state).unwrap().group_rom_handoff_proposals[&proposal.group_id],
            proposal
        );
        state.group_rom_handoff_proposals.clear();
        state
            .group_rom_handoff_proposals
            .insert(uuid_id(999, GroupId::new), proposal.clone());
        assert!(decode(&state).is_err());
        state.group_rom_handoff_proposals.clear();
        let mut invalid = proposal.clone();
        invalid.members = [Some(intent().members[1]), Some(intent().members[0])];
        state
            .group_rom_handoff_proposals
            .insert(invalid.group_id, invalid);
        assert!(decode(&state).is_err());
    }

    fn decode(state: &State) -> Result<State, ciborium::de::Error<std::io::Error>> {
        let mut bytes = Vec::new();
        ciborium::into_writer(state, &mut bytes).unwrap();
        ciborium::from_reader(bytes.as_slice())
    }

    fn committed_record(intent: &GroupRomHandoffIntent, index: usize) -> SnapshotRecord {
        let source = intent.members[index];
        let pending =
            SnapshotFile::from_bytes(coop_cloud::ArtifactIdentity::PendingCommits, b"[]").unwrap();
        SnapshotRecord::new(
            uuid_id(300 + index as u128, SnapshotId::new),
            intent.destination_world_id,
            SnapshotFence::new(
                source.fence.session_id,
                source.fence.character_id,
                source.fence.session_epoch,
            ),
            source.fence.current_revision,
            Revision::new(2),
            vec![
                SnapshotFile::from_bytes(coop_cloud::ArtifactIdentity::CharacterSav, b"save")
                    .unwrap(),
                pending.clone(),
            ],
            pending.sha256,
            None,
            UnixTimestampMillis::new(1_700_000_001_000),
        )
        .unwrap()
    }

    #[test]
    fn paired_stage_and_abort_receipt_survive_cbor_restart() {
        let stage = stage();
        let group_id = stage.intent.group_id;
        let key = stage.intent.idempotency_key;
        let mut state = State::default();
        state
            .group_rom_handoff_stages
            .insert(group_id, stage.clone());
        state.group_rom_handoff_receipts.insert(
            (group_id, key),
            GroupRomHandoffReceipt::Aborted {
                intent: stage.intent.clone(),
                stage_ids: stage.stage_ids,
                client_intent_keys: stage.client_intent_keys,
                resolved_at: 1_700_000_001_000,
            },
        );
        let recovered = decode(&state).unwrap();
        assert_eq!(recovered.group_rom_handoff_stages[&group_id], stage);
        assert!(matches!(
            recovered.group_rom_handoff_receipts[&(group_id, key)],
            GroupRomHandoffReceipt::Aborted { .. }
        ));
    }

    #[test]
    fn paired_stage_decode_rejects_mismatched_key_or_stage_and_oversize_map() {
        let mut state = State::default();
        let stage = stage();
        state
            .group_rom_handoff_stages
            .insert(uuid_id(900, GroupId::new), stage.clone());
        assert!(decode(&state).is_err());

        state.group_rom_handoff_stages.clear();
        let mut invalid = stage.clone();
        invalid.stage_ids[1] = invalid.stage_ids[0];
        state
            .group_rom_handoff_stages
            .insert(invalid.intent.group_id, invalid);
        assert!(decode(&state).is_err());

        state.group_rom_handoff_stages.clear();
        for number in 0..=MAX_GROUP_ROM_HANDOFF_STAGES {
            let mut member = stage.clone();
            let id = uuid_id(1_000 + number as u128, GroupId::new);
            member.intent.group_id = id;
            state.group_rom_handoff_stages.insert(id, member);
        }
        assert!(decode(&state).is_err());
    }

    #[test]
    fn paired_receipt_decode_rejects_wrong_replay_key() {
        let stage = stage();
        let mut state = State::default();
        state.group_rom_handoff_receipts.insert(
            (stage.intent.group_id, uuid_id(999, IdempotencyKey::new)),
            GroupRomHandoffReceipt::Aborted {
                intent: stage.intent,
                stage_ids: stage.stage_ids,
                client_intent_keys: stage.client_intent_keys,
                resolved_at: 1_700_000_001_000,
            },
        );
        assert!(decode(&state).is_err());
    }

    #[test]
    fn paired_commit_receipt_replays_both_authoritative_heads() {
        let intent = intent();
        let records = [committed_record(&intent, 0), committed_record(&intent, 1)];
        let mut state = State::default();
        state.group_rom_handoff_receipts.insert(
            (intent.group_id, intent.idempotency_key),
            GroupRomHandoffReceipt::Committed {
                intent: intent.clone(),
                snapshots: records.clone(),
                destination_zone: WorldZone::new(
                    RegionId::Cormoria,
                    "CORMORIA_RIVETSHORE_CITY_HARBOR",
                    1,
                )
                .unwrap(),
                group_zone_revision: 2,
                client_intent_keys: None,
                resolved_at: 1_700_000_001_000,
            },
        );
        let recovered = decode(&state).unwrap();
        assert!(matches!(
            &recovered.group_rom_handoff_receipts[&(intent.group_id, intent.idempotency_key)],
            GroupRomHandoffReceipt::Committed { snapshots, .. } if *snapshots == records
        ));
    }

    #[test]
    fn paired_receipt_retention_gc_is_bounded_and_clock_monotonic() {
        let stage = stage();
        let group_id = stage.intent.group_id;
        let now = 1_800_000_000_000;
        let old_key = uuid_id(8_001, IdempotencyKey::new);
        let recent_key = uuid_id(8_002, IdempotencyKey::new);
        let old = GroupRomHandoffReceipt::Aborted {
            intent: stage.intent.clone(),
            stage_ids: stage.stage_ids,
            client_intent_keys: None,
            resolved_at: now - GROUP_ROM_HANDOFF_RECEIPT_RETENTION_MS - 1,
        };
        let recent = GroupRomHandoffReceipt::Aborted {
            intent: stage.intent.clone(),
            stage_ids: stage.stage_ids,
            client_intent_keys: None,
            resolved_at: now,
        };
        let mut state = State::default();
        state
            .group_rom_handoff_receipts
            .insert((group_id, old_key), old);
        state
            .group_rom_handoff_receipts
            .insert((group_id, recent_key), recent.clone());
        state.group_rom_handoff_receipt_high_water = now;
        prune_group_rom_handoff_receipts(&mut state, now - 1);
        assert!(!state
            .group_rom_handoff_receipts
            .contains_key(&(group_id, old_key)));
        assert!(state
            .group_rom_handoff_receipts
            .contains_key(&(group_id, recent_key)));

        for index in 0..MAX_GROUP_ROM_HANDOFF_RECEIPTS {
            state.group_rom_handoff_receipts.insert(
                (
                    group_id,
                    uuid_id(10_000 + index as u128, IdempotencyKey::new),
                ),
                recent.clone(),
            );
        }
        let terminal_key = uuid_id(20_000, IdempotencyKey::new);
        assert_eq!(
            record_group_rom_handoff_receipt(&mut state, (group_id, terminal_key), recent, now),
            Err(StorageError::Busy)
        );
        assert_eq!(
            state.group_rom_handoff_receipts.len(),
            MAX_GROUP_ROM_HANDOFF_RECEIPTS + 1
        );
        assert!(!state
            .group_rom_handoff_receipts
            .contains_key(&(group_id, terminal_key)));

        let next_now = now + GROUP_ROM_HANDOFF_RECEIPT_RETENTION_MS + 1;
        prune_group_rom_handoff_receipts(&mut state, next_now);
        assert_eq!(
            record_group_rom_handoff_receipt(
                &mut state,
                (group_id, terminal_key),
                GroupRomHandoffReceipt::Aborted {
                    intent: stage.intent,
                    stage_ids: stage.stage_ids,
                    client_intent_keys: None,
                    resolved_at: next_now,
                },
                next_now,
            ),
            Ok(())
        );
    }

    #[test]
    fn paired_receipt_reservation_counts_toward_terminal_capacity() {
        let stage = stage();
        let group_id = stage.intent.group_id;
        let now = 1_800_000_000_000;
        let receipt = GroupRomHandoffReceipt::Aborted {
            intent: stage.intent.clone(),
            stage_ids: stage.stage_ids,
            client_intent_keys: None,
            resolved_at: now,
        };
        let mut state = State::default();
        state.group_rom_handoff_receipt_high_water = now;
        for index in 0..MAX_GROUP_ROM_HANDOFF_RECEIPTS - 1 {
            state.group_rom_handoff_receipts.insert(
                (
                    group_id,
                    uuid_id(30_000 + index as u128, IdempotencyKey::new),
                ),
                receipt.clone(),
            );
        }
        let terminal_key = uuid_id(40_000, IdempotencyKey::new);
        assert_eq!(
            reserve_group_rom_handoff_receipt(&mut state, (group_id, terminal_key), now),
            Ok(())
        );
        assert!(state
            .group_rom_handoff_receipt_reservations
            .contains_key(&group_id));
        let other_group = uuid_id(40_001, GroupId::new);
        assert_eq!(
            reserve_group_rom_handoff_receipt(&mut state, (other_group, terminal_key), now),
            Err(StorageError::Busy)
        );

        let mut terminal_intent = stage.intent.clone();
        terminal_intent.idempotency_key = terminal_key;
        assert_eq!(
            record_group_rom_handoff_receipt(
                &mut state,
                (group_id, terminal_key),
                GroupRomHandoffReceipt::Aborted {
                    intent: terminal_intent,
                    stage_ids: stage.stage_ids,
                    client_intent_keys: None,
                    resolved_at: now,
                },
                now,
            ),
            Ok(())
        );
        assert!(!state
            .group_rom_handoff_receipt_reservations
            .contains_key(&group_id));
        assert_eq!(
            state.group_rom_handoff_receipts.len(),
            MAX_GROUP_ROM_HANDOFF_RECEIPTS
        );
    }
}
