"""Install pinned Cormoria tileset sources and verify the self-contained build inputs.

Installation reads authenticated donor stages once. Normal builds and --check
use only files committed inside the host repository.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

from tools.cormoria import import_world, materialize_tileset_preview, register_tilesets

ROOT = Path(__file__).resolve().parents[2]
PLAN = Path("data/tilesets/cormoria/asset_plan.json")
HEADER = Path("src/data/tilesets/cormoria_imported.h")
RULES = Path("data/tilesets/cormoria/rules.mk")
PINNED_PLAN_SHA256 = "552c932a6406f8bef686e887984e46b1c51703df6957fafe34fc8809a7f2635f"
PINNED_HEADER_SHA256 = "cbe15f03ea42305166d1b006f4e888734d6235d578e2915bf333984371666453"


class InstallError(ValueError):
    """An installed source or conversion rule differs from the pinned preview."""


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def normalized_text(data: bytes) -> bytes:
    if b"\r" in data.replace(b"\r\n", b""):
        raise InstallError("invalid generated text line endings")
    return data.replace(b"\r\n", b"\n")


def rules_from_plan(plan: dict) -> bytes:
    lines = ["# Authenticated Cormoria tile-count conversions; generated by install_tilesets.py.", ""]
    overridden = [row for row in plan["recipes"] if "num_tiles" in row]
    if len(overridden) != 28:
        raise InstallError("donor tile-count rule inventory drifted")
    for row in sorted(overridden, key=lambda item: item["target"]):
        target = row["target"].removesuffix(".lz")
        if (row["conversion"] != "png->4bpp->lz" or not target.endswith(".4bpp")
                or not target.startswith("data/tilesets/cormoria/")
                or not isinstance(row["num_tiles"], int) or row["num_tiles"] <= 0):
            raise InstallError(f"invalid donor tile-count recipe: {row['target']}")
        lines.extend([f"{target}: %.4bpp: %.png",
                      f"\t$(GFX) $< $@ -num_tiles {row['num_tiles']} -Wnum_tiles", ""])
    return ("\n".join(lines) + "\n").encode("utf-8")


def _installed_path(root: Path, relative: Path) -> Path:
    path = root / relative
    if not path.resolve().is_relative_to(root.resolve()):
        raise InstallError(f"installed path escapes repository: {relative}")
    return path


def install(stage: Path, foundation: Path, donor_rules: Path, donor_anims: Path,
            output_root: Path = ROOT, source_root: Path = ROOT) -> int:
    stage = stage.resolve(strict=True)
    foundation = foundation.resolve(strict=True)
    output_root = output_root.resolve()
    rendered = register_tilesets.render(stage, foundation, donor_rules, donor_anims, source_root)
    if (sha(rendered["asset_plan.json"]) != PINNED_PLAN_SHA256
            or sha(rendered["tilesets.c"]) != PINNED_HEADER_SHA256):
        raise InstallError("authenticated preview differs from pinned installation")
    plan = json.loads(rendered["asset_plan.json"])
    pending: list[tuple[Path, bytes]] = [(PLAN, rendered["asset_plan.json"]),
                                          (HEADER, rendered["tilesets.c"]),
                                          (RULES, rules_from_plan(plan))]
    seen = {PLAN, HEADER, RULES}
    for recipe in plan["recipes"]:
        relative = import_world.safe_relative(materialize_tileset_preview.source_target(recipe))
        if relative in seen or not relative.as_posix().startswith("data/tilesets/cormoria/"):
            raise InstallError(f"duplicate or unsafe installed input: {relative}")
        seen.add(relative)
        origin = {"stage": stage, "general-foundation": foundation}.get(recipe["origin"])
        if origin is None:
            raise InstallError(f"unknown source origin: {recipe['origin']}")
        source = (origin / import_world.safe_relative(recipe["source"])).resolve()
        if not source.is_relative_to(origin) or not source.is_file():
            raise InstallError(f"missing authenticated source: {recipe['source']}")
        data = source.read_bytes()
        if sha(data) != recipe["source_sha256"]:
            raise InstallError(f"authenticated source drifted: {recipe['source']}")
        pending.append((relative, data))
    for relative, data in pending:
        destination = _installed_path(output_root, relative)
        if destination.exists() and destination.read_bytes() != data:
            raise InstallError(f"refusing to overwrite differing installed file: {relative}")
    for relative, data in pending:
        destination = _installed_path(output_root, relative)
        destination.parent.mkdir(parents=True, exist_ok=True)
        if not destination.exists():
            destination.write_bytes(data)
    return len(plan["recipes"])


def check_installed(root: Path = ROOT) -> int:
    root = root.resolve(strict=True)
    plan_bytes = normalized_text(_installed_path(root, PLAN).read_bytes())
    header_bytes = normalized_text(_installed_path(root, HEADER).read_bytes())
    if sha(plan_bytes) != PINNED_PLAN_SHA256 or sha(header_bytes) != PINNED_HEADER_SHA256:
        raise InstallError("installed plan or tileset header differs from pinned preview")
    plan = json.loads(plan_bytes)
    rules = normalized_text(_installed_path(root, RULES).read_bytes())
    if rules != rules_from_plan(plan):
        raise InstallError("installed donor tile-count rules drifted")
    seen: set[Path] = set()
    for recipe in plan["recipes"]:
        relative = import_world.safe_relative(materialize_tileset_preview.source_target(recipe))
        if relative in seen:
            raise InstallError(f"duplicate installed input: {relative}")
        seen.add(relative)
        data = _installed_path(root, relative).read_bytes()
        if sha(data) != recipe["source_sha256"]:
            raise InstallError(f"installed source hash mismatch: {relative}")
    if len(seen) != 1058:
        raise InstallError("installed source count drifted")
    return len(seen)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--stage", type=Path)
    parser.add_argument("--general-foundation", type=Path)
    parser.add_argument("--donor-rules", type=Path)
    parser.add_argument("--donor-anims", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    try:
        if args.check:
            count = check_installed()
            print(f"Verified {count} self-contained Cormoria tileset sources")
        else:
            if not all((args.stage, args.general_foundation, args.donor_rules, args.donor_anims)):
                parser.error("install requires --stage, --general-foundation, --donor-rules, and --donor-anims")
            count = install(args.stage, args.general_foundation, args.donor_rules, args.donor_anims)
            print(f"Installed {count} authenticated Cormoria tileset sources")
    except (OSError, ValueError, KeyError) as exc:
        print(f"Cormoria tileset installation: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
