#ifndef GUARD_CONSTANTS_JOHTO_BERRY_PLOTS_H
#define GUARD_CONSTANTS_JOHTO_BERRY_PLOTS_H

#define JOHTO_BERRY_TREE_CHERI_2 90
#define JOHTO_BERRY_TREE_PECHA_2 91
#define JOHTO_BERRY_TREE_ORAN_1 92
#define JOHTO_BERRY_TREE_ROUTE_102_ORAN 93
#define JOHTO_BERRY_TREE_ORAN_2 94
#define JOHTO_BERRY_TREE_CHERI_1 95
#define JOHTO_BERRY_TREE_PECHA_1 96
#define JOHTO_BERRY_TREE_PERSIM_1 97
#define JOHTO_BERRY_TREE_PERSIM_2 98
#define JOHTO_BERRY_TREE_CHESTO_1 99
#define JOHTO_BERRY_TREE_RAWST_1 100
#define JOHTO_BERRY_TREE_RAWST_2 101
#define JOHTO_BERRY_TREE_CHESTO_2 102
#define JOHTO_BERRY_TREE_LEPPA_1 103
#define JOHTO_BERRY_TREE_LEPPA_2 104
#define JOHTO_BERRY_TREE_ASPEAR_1 105
#define JOHTO_BERRY_TREE_ASPEAR_2 106
#define JOHTO_BERRY_TREE_LUM_1 107
#define JOHTO_BERRY_TREE_SITRUS_1 108
#define JOHTO_BERRY_TREE_ROUTE_118_SITRUS_1 109

#define JOHTO_BERRY_PLOTS_COUNT 20
#define JOHTO_BERRY_PLOTS_FIRST 90
#define JOHTO_BERRY_PLOTS_LAST 109

#define JOHTO_BERRY_HARVEST_UNAVAILABLE 0
#define JOHTO_BERRY_HARVEST_SUCCESS 1
#define JOHTO_BERRY_HARVEST_BAG_FULL 2

#endif
