#ifndef GUARD_CORMORIA_HEAL_LOCATIONS_H
#define GUARD_CORMORIA_HEAL_LOCATIONS_H

#include "constants/heal_locations.h"

// The donor's 18 outdoor heal coordinates are appended only in the Cormoria ROM.
enum {
    HEAL_LOCATION_CORMORIA_CARABRUE_TOWN = NUM_HEAL_LOCATIONS,
    HEAL_LOCATION_CORMORIA_FENNILAHL_TOWN,
    HEAL_LOCATION_CORMORIA_GASTREE_CITY,
    HEAL_LOCATION_CORMORIA_CERAM_BASE_CAMP,
    HEAL_LOCATION_CORMORIA_ANCIENT_CERAM,
    HEAL_LOCATION_CORMORIA_GALECREST_CITY,
    HEAL_LOCATION_CORMORIA_SILVERSUN_CITY,
    HEAL_LOCATION_CORMORIA_PELLUCA_CITY,
    HEAL_LOCATION_CORMORIA_MIRROH_BASE_CAMP,
    HEAL_LOCATION_CORMORIA_WINTERLILY_HOLLOW,
    HEAL_LOCATION_CORMORIA_ANCIENT_MIRROH,
    HEAL_LOCATION_CORMORIA_RIVETSHORE_CITY,
    HEAL_LOCATION_CORMORIA_SSELEGANT,
    HEAL_LOCATION_CORMORIA_UNCHARTED_ISLAND,
    HEAL_LOCATION_CORMORIA_ANCIENT_CORMORIA_FINAL_ISLAND,
    HEAL_LOCATION_CORMORIA_VICTORY_CAPE,
    HEAL_LOCATION_CORMORIA_CHAMPIONSHIP_CORRIDOR,
    NUM_CORMORIA_HEAL_LOCATIONS,
};

#endif
