Cormoria_gText_ObtainedTheItem::
	.string "Obtained the {STR_VAR_2}!$"

Cormoria_gText_TheBagIsFull::
	.string "The BAG is full…$"

Cormoria_gText_PutItemInPocket::
	.string "{PLAYER} put away the {STR_VAR_2}\n"
	.string "in the {STR_VAR_3} Pocket.$"

Cormoria_gText_PlayerFoundOneItem::
	.string "{PLAYER} found one {STR_VAR_2}!$"

Cormoria_gText_TooBadBagIsFull::
	.string "Too bad!\n"
	.string "The BAG is full…$"

Cormoria_gText_PlayerPutItemInBag::
	.string "{PLAYER} put away the {STR_VAR_2}\n"
	.string "in the BAG.$"

Cormoria_gText_ObtainedTheDecor::
	.string "Obtained the {STR_VAR_2}!$"

Cormoria_gText_NoRoomLeftForAnother::
	.string "Too bad! There's no room left for\n"
	.string "another {STR_VAR_2}…$"

Cormoria_gText_TheDecorWasTransferredToThePC::
	.string "The {STR_VAR_2} was transferred\n"
	.string "to the PC.$"

Cormoria_gText_ObtainedTheItems::
	.string "Obtained {STR_VAR_1} {STR_VAR_2}!$"

Cormoria_gText_PlayerFoundItems::
	.string "{PLAYER} found {STR_VAR_1} {STR_VAR_2}!$"
