#ifndef GUARD_COOP_GROUP_TRAVEL_PROTOCOL_H
#define GUARD_COOP_GROUP_TRAVEL_PROTOCOL_H

#include "gba/types.h"

#define COOP_GROUP_TRAVEL_RECORD_SIZE 32

enum CoopGroupTravelRoute { COOP_GROUP_TRAVEL_ROUTE_TRAIN_ORIGINAL = 1, COOP_GROUP_TRAVEL_ROUTE_TRAIN_LATER, COOP_GROUP_TRAVEL_ROUTE_FERRY_ORIGINAL, COOP_GROUP_TRAVEL_ROUTE_FERRY_LATER, COOP_GROUP_TRAVEL_ROUTE_GATE_ORIGINAL, COOP_GROUP_TRAVEL_ROUTE_GATE_LATER };
enum CoopGroupTravelEra { COOP_GROUP_TRAVEL_ERA_ORIGINAL = 1, COOP_GROUP_TRAVEL_ERA_LATER };
enum CoopGroupTravelDestination { COOP_GROUP_TRAVEL_DEST_ORIGINAL_VERMILION = 1, COOP_GROUP_TRAVEL_DEST_LATER_VERMILION, COOP_GROUP_TRAVEL_DEST_ORIGINAL_SAFFRON, COOP_GROUP_TRAVEL_DEST_LATER_SAFFRON, COOP_GROUP_TRAVEL_DEST_ORIGINAL_ROUTE22, COOP_GROUP_TRAVEL_DEST_LATER_ROUTE22 };
enum CoopGroupTravelResult { COOP_GROUP_TRAVEL_RESULT_NONE, COOP_GROUP_TRAVEL_RESULT_ACCEPTED, COOP_GROUP_TRAVEL_RESULT_DECLINED, COOP_GROUP_TRAVEL_RESULT_APPLIED };
enum CoopGroupTravelReason { COOP_GROUP_TRAVEL_REASON_NONE, COOP_GROUP_TRAVEL_REASON_PARTICIPANT_DECLINED, COOP_GROUP_TRAVEL_REASON_REQUESTER_CANCELED, COOP_GROUP_TRAVEL_REASON_CONFLICT, COOP_GROUP_TRAVEL_REASON_UNSAFE };
enum CoopGroupTravelClientKind { COOP_GROUP_TRAVEL_CLIENT_REQUEST = 1, COOP_GROUP_TRAVEL_CLIENT_DECISION, COOP_GROUP_TRAVEL_CLIENT_CANCEL, COOP_GROUP_TRAVEL_CLIENT_APPLIED };
enum CoopGroupTravelServerKind { COOP_GROUP_TRAVEL_SERVER_REQUESTING = 1, COOP_GROUP_TRAVEL_SERVER_OFFER, COOP_GROUP_TRAVEL_SERVER_COMMIT, COOP_GROUP_TRAVEL_SERVER_ABORT, COOP_GROUP_TRAVEL_SERVER_COMPLETE };

struct CoopGroupTravelRecord
{
    u8 kind, route, era, destination, result, reason;
    u8 departure;
    u8 reserved0;
    u32 request_id;
    u8 proposal_id[16];
    u8 reserved1[4];
};

_Static_assert(sizeof(struct CoopGroupTravelRecord) == COOP_GROUP_TRAVEL_RECORD_SIZE, "group travel wire size");

bool8 CoopGroupTravelProtocol_ValidateClient(const struct CoopGroupTravelRecord *record);
bool8 CoopGroupTravelProtocol_ValidateServer(const struct CoopGroupTravelRecord *record);

#endif
