Cormoria_PellucaCityPokemart_MapScripts::
	.byte 0


Cormoria_PellucaCityPokemart_NPC1::
# 5 "data//maps/PellucaCityPokemart/scripts.pory"
	msgbox Cormoria_PellucaCityPokemart_NPC1_Text_0, MSGBOX_NPC
	return


Cormoria_PellucaCityPokemart_NPC1_Text_0:
# 5 "data//maps/PellucaCityPokemart/scripts.pory"
	.string "I'm stocking up on Revives for my\n"
	.string "battle against Gym Leader Jania!\n"
	.string "After I beat her, I'll need just one more\l"
	.string "badge to enter the Pokémon\l"
	.string "Championship!\p"
	.string "...after I beat her...$"
