// Outdoor coordinates copied from Dreamstone Mysteries f7997186, IDs 23-40.
// The donor has no Cormoria Pokemon Center respawn data for these locations.
static const struct HealLocation sCormoriaHealLocations[] =
{
    {MAP_GROUP(MAP_CORMORIA_CARABRUE_TOWN), MAP_NUM(MAP_CORMORIA_CARABRUE_TOWN), 7, 9},
    {MAP_GROUP(MAP_CORMORIA_FENNILAHL_TOWN), MAP_NUM(MAP_CORMORIA_FENNILAHL_TOWN), 14, 16},
    {MAP_GROUP(MAP_CORMORIA_GASTREE_CITY), MAP_NUM(MAP_CORMORIA_GASTREE_CITY), 16, 17},
    {MAP_GROUP(MAP_CORMORIA_CERAM_BASE_CAMP), MAP_NUM(MAP_CORMORIA_CERAM_BASE_CAMP), 21, 34},
    {MAP_GROUP(MAP_CORMORIA_ANCIENT_CERAM), MAP_NUM(MAP_CORMORIA_ANCIENT_CERAM), 59, 39},
    {MAP_GROUP(MAP_CORMORIA_GALECREST_CITY), MAP_NUM(MAP_CORMORIA_GALECREST_CITY), 32, 47},
    {MAP_GROUP(MAP_CORMORIA_SILVERSUN_CITY), MAP_NUM(MAP_CORMORIA_SILVERSUN_CITY), 25, 22},
    {MAP_GROUP(MAP_CORMORIA_PELLUCA_CITY), MAP_NUM(MAP_CORMORIA_PELLUCA_CITY), 14, 28},
    {MAP_GROUP(MAP_CORMORIA_MIRROH_BASE_CAMP), MAP_NUM(MAP_CORMORIA_MIRROH_BASE_CAMP), 12, 10},
    {MAP_GROUP(MAP_CORMORIA_WINTERLILY_HOLLOW), MAP_NUM(MAP_CORMORIA_WINTERLILY_HOLLOW), 18, 10},
    {MAP_GROUP(MAP_CORMORIA_ANCIENT_MIRROH), MAP_NUM(MAP_CORMORIA_ANCIENT_MIRROH), 12, 23},
    {MAP_GROUP(MAP_CORMORIA_RIVETSHORE_CITY), MAP_NUM(MAP_CORMORIA_RIVETSHORE_CITY), 24, 14},
    {MAP_GROUP(MAP_CORMORIA_SSELEGANT), MAP_NUM(MAP_CORMORIA_SSELEGANT), 19, 23},
    {MAP_GROUP(MAP_CORMORIA_UNCHARTED_ISLAND), MAP_NUM(MAP_CORMORIA_UNCHARTED_ISLAND), 59, 57},
    {MAP_GROUP(MAP_CORMORIA_ANCIENT_CORMORIA_FINAL_ISLAND), MAP_NUM(MAP_CORMORIA_ANCIENT_CORMORIA_FINAL_ISLAND), 9, 6},
    {MAP_GROUP(MAP_CORMORIA_CHAMPIONSHIP), MAP_NUM(MAP_CORMORIA_CHAMPIONSHIP), 25, 28},
    {MAP_GROUP(MAP_CORMORIA_CHAMPIONSHIP_CORRIDOR), MAP_NUM(MAP_CORMORIA_CHAMPIONSHIP_CORRIDOR), 7, 10},
};
