//! Product independent coordination for a two client save handoff.
//!
//! The HTTP route and the server repository deliberately do not appear here.
//! This module is the local safety seam those adapters use once both clients
//! have reached an authenticated checkpoint.  It keeps the old source heads
//! immutable until one paired receipt is observed and both replacement heads
//! have been adopted.

use coop_cloud::{
    CharacterId, GroupId, IdempotencyKey, LeaseFence, Revision, SessionId, Sha256Digest,
    SnapshotId, TradeOfferId,
};
use thiserror::Error;

pub const TRADE_PARTICIPANTS: usize = 2;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct TradeSourceHead {
    pub character_id: CharacterId,
    pub session_id: SessionId,
    pub snapshot_id: SnapshotId,
    pub revision: Revision,
    pub fence: LeaseFence,
    pub save_sha256: Sha256Digest,
    pub pending_commits_sha256: Sha256Digest,
}

impl TradeSourceHead {
    fn validate(self, expected_character: CharacterId) -> Result<(), TradeHandoffError> {
        if self.character_id != expected_character
            || self.fence.character_id != self.character_id
            || self.fence.session_id != self.session_id
            || self.fence.current_revision != self.revision
            || self.revision.is_initial()
        {
            return Err(TradeHandoffError::SourceMismatch);
        }
        Ok(())
    }
}

/// The server returns this typed identity for each newly published snapshot.
/// Artifact bytes are fetched and verified by the session owner before it
/// calls [`TradeHandoff::adopt`].
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct TradePublishedHead {
    pub character_id: CharacterId,
    pub snapshot_id: SnapshotId,
    pub revision: Revision,
    pub save_sha256: Sha256Digest,
    pub pending_commits_sha256: Sha256Digest,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct TradeCommitReceipt {
    pub offer_id: TradeOfferId,
    pub idempotency_key: IdempotencyKey,
    pub outputs: [TradePublishedHead; TRADE_PARTICIPANTS],
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct TradeStageToken {
    pub offer_id: TradeOfferId,
    pub idempotency_key: IdempotencyKey,
    pub sources: [TradeSourceHead; TRADE_PARTICIPANTS],
}

/// A heartbeat proof is deliberately supplied by the authenticated cloud
/// adapter rather than generated by the coordinator.  This prevents a local
/// clock or a stale lease from authorizing a handoff.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct TradeHeartbeat {
    pub fence: LeaseFence,
    pub expires_at_ms: u64,
}

impl TradeHeartbeat {
    fn validate(
        self,
        source: TradeSourceHead,
        revision: Revision,
        now_ms: u64,
    ) -> Result<(), TradeHandoffError> {
        if self.fence.session_id != source.session_id
            || self.fence.character_id != source.character_id
            || self.fence.client_instance_id != source.fence.client_instance_id
            || self.fence.session_epoch != source.fence.session_epoch
            || self.fence.current_revision != revision
            || self.expires_at_ms <= now_ms
        {
            return Err(TradeHandoffError::LeaseNotHealthy);
        }
        Ok(())
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum TradePhase {
    Quiescing,
    Staging,
    Publishing,
    Adopting,
    Complete,
    Aborted,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TradeRecoveryJournal {
    pub offer_id: TradeOfferId,
    pub group_id: GroupId,
    pub idempotency_key: IdempotencyKey,
    pub members: [CharacterId; TRADE_PARTICIPANTS],
    pub phase: TradePhase,
    pub sources: [Option<TradeSourceHead>; TRADE_PARTICIPANTS],
    /// The lease fences observed when the pair entered publication.  Keeping
    /// these across a restart prevents an unanswered publish from being
    /// mistaken for a safe pre-publish cancellation.
    pub publish_fences: [Option<LeaseFence>; TRADE_PARTICIPANTS],
    pub receipt: Option<TradeCommitReceipt>,
    pub adopted: [bool; TRADE_PARTICIPANTS],
}

#[derive(Debug, Error, Eq, PartialEq)]
pub enum TradeHandoffError {
    #[error("trade must have exactly two distinct participants")]
    InvalidParticipants,
    #[error("trade handoff is not in the required phase")]
    InvalidPhase,
    #[error("trade source does not match the anchored lease head")]
    SourceMismatch,
    #[error("ordinary save commits are fenced during trade handoff")]
    SaveFenced,
    #[error("lease heartbeat is missing, expired, or has the wrong fence")]
    LeaseNotHealthy,
    #[error("trade stage token does not match the anchored sources")]
    StageMismatch,
    #[error("trade receipt does not match the staged pair")]
    ReceiptMismatch,
    #[error("replacement head does not match the paired receipt")]
    ReplacementMismatch,
    #[error("trade recovery journal is inconsistent")]
    RecoveryMismatch,
}

/// Coordinates the local half of a paired trade.  The coordinator is small
/// and intentionally synchronous: a route adapter can await network calls
/// between the transitions, while this object remains the single authority
/// for local save fencing and crash recovery.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TradeHandoff {
    offer_id: TradeOfferId,
    group_id: GroupId,
    idempotency_key: IdempotencyKey,
    members: [CharacterId; TRADE_PARTICIPANTS],
    phase: TradePhase,
    sources: [Option<TradeSourceHead>; TRADE_PARTICIPANTS],
    publish_fences: [Option<LeaseFence>; TRADE_PARTICIPANTS],
    receipt: Option<TradeCommitReceipt>,
    adopted: [bool; TRADE_PARTICIPANTS],
}

impl TradeHandoff {
    pub fn begin(
        offer_id: TradeOfferId,
        group_id: GroupId,
        idempotency_key: IdempotencyKey,
        members: [CharacterId; TRADE_PARTICIPANTS],
    ) -> Result<Self, TradeHandoffError> {
        if members[0] == members[1] {
            return Err(TradeHandoffError::InvalidParticipants);
        }
        Ok(Self {
            offer_id,
            group_id,
            idempotency_key,
            members,
            phase: TradePhase::Quiescing,
            sources: [None, None],
            publish_fences: [None, None],
            receipt: None,
            adopted: [false, false],
        })
    }

    #[must_use]
    pub const fn phase(&self) -> TradePhase {
        self.phase
    }

    #[must_use]
    pub const fn offer_id(&self) -> TradeOfferId {
        self.offer_id
    }

    #[must_use]
    pub const fn group_id(&self) -> GroupId {
        self.group_id
    }

    #[must_use]
    pub const fn idempotency_key(&self) -> IdempotencyKey {
        self.idempotency_key
    }

    #[must_use]
    pub const fn members(&self) -> [CharacterId; TRADE_PARTICIPANTS] {
        self.members
    }

    #[must_use]
    pub const fn receipt(&self) -> Option<TradeCommitReceipt> {
        self.receipt
    }

    /// Returns whether this participant may still write an ordinary save.
    /// Once a participant has emitted its exact checkpoint head, every later
    /// save is fenced until adoption or an explicit abort before publication.
    #[must_use]
    pub fn ordinary_save_permitted(&self, participant: usize) -> bool {
        if participant >= TRADE_PARTICIPANTS {
            return false;
        }
        match self.phase {
            TradePhase::Quiescing => self.sources[participant].is_none(),
            TradePhase::Aborted | TradePhase::Complete => true,
            TradePhase::Staging | TradePhase::Publishing | TradePhase::Adopting => false,
        }
    }

    pub fn require_ordinary_save_permit(
        &self,
        participant: usize,
    ) -> Result<(), TradeHandoffError> {
        if self.ordinary_save_permitted(participant) {
            Ok(())
        } else {
            Err(TradeHandoffError::SaveFenced)
        }
    }

    /// Records an authenticated checkpoint head.  The caller must not release
    /// the emulator's quiesce latch after this returns successfully.
    pub fn record_quiesced(
        &mut self,
        participant: usize,
        source: TradeSourceHead,
        heartbeat: TradeHeartbeat,
        now_ms: u64,
    ) -> Result<(), TradeHandoffError> {
        if self.phase != TradePhase::Quiescing || participant >= TRADE_PARTICIPANTS {
            return Err(TradeHandoffError::InvalidPhase);
        }
        source.validate(self.members[participant])?;
        heartbeat.validate(source, source.revision, now_ms)?;
        if self.sources[participant].is_some() {
            return Err(TradeHandoffError::SourceMismatch);
        }
        self.sources[participant] = Some(source);
        if self.sources.iter().all(Option::is_some) {
            self.phase = TradePhase::Staging;
        }
        Ok(())
    }

    #[must_use]
    pub fn stage_token(&self) -> Option<TradeStageToken> {
        if self.phase != TradePhase::Staging {
            return None;
        }
        Some(TradeStageToken {
            offer_id: self.offer_id,
            idempotency_key: self.idempotency_key,
            sources: [self.sources[0]?, self.sources[1]?],
        })
    }

    /// Confirms that the server staged exactly the two source heads.  No local
    /// save is changed by staging.
    pub fn mark_staged(
        &mut self,
        token: TradeStageToken,
        heartbeats: [TradeHeartbeat; TRADE_PARTICIPANTS],
        now_ms: u64,
    ) -> Result<(), TradeHandoffError> {
        if self.phase != TradePhase::Staging {
            return Err(TradeHandoffError::InvalidPhase);
        }
        let expected = self.stage_token().ok_or(TradeHandoffError::StageMismatch)?;
        if token != expected {
            return Err(TradeHandoffError::StageMismatch);
        }
        let mut publish_fences = [None, None];
        for (index, heartbeat) in heartbeats.into_iter().enumerate() {
            heartbeat.validate(
                self.sources[index].ok_or(TradeHandoffError::StageMismatch)?,
                self.sources[index]
                    .ok_or(TradeHandoffError::StageMismatch)?
                    .revision,
                now_ms,
            )?;
            publish_fences[index] = Some(heartbeat.fence);
        }
        self.publish_fences = publish_fences;
        self.phase = TradePhase::Publishing;
        Ok(())
    }

    /// Accepts only one paired publication. A retry with the exact same
    /// receipt is idempotent; a changed receipt is rejected.
    pub fn mark_published(
        &mut self,
        receipt: TradeCommitReceipt,
        heartbeats: [TradeHeartbeat; TRADE_PARTICIPANTS],
        now_ms: u64,
    ) -> Result<(), TradeHandoffError> {
        if self.phase != TradePhase::Publishing && self.phase != TradePhase::Adopting {
            return Err(TradeHandoffError::InvalidPhase);
        }
        if receipt.offer_id != self.offer_id || receipt.idempotency_key != self.idempotency_key {
            return Err(TradeHandoffError::ReceiptMismatch);
        }
        let sources = [
            self.sources[0].ok_or(TradeHandoffError::ReceiptMismatch)?,
            self.sources[1].ok_or(TradeHandoffError::ReceiptMismatch)?,
        ];
        let mut publish_fences = [None, None];
        for (index, heartbeat) in heartbeats.into_iter().enumerate() {
            let output = receipt.outputs[index];
            if output.character_id != sources[index].character_id
                || output.revision
                    != sources[index]
                        .revision
                        .next()
                        .map_err(|_| TradeHandoffError::ReceiptMismatch)?
                || output.snapshot_id == sources[index].snapshot_id
            {
                return Err(TradeHandoffError::ReceiptMismatch);
            }
            // A publish response may race the lease heartbeat that advances
            // the server head. Accept either the anchored source revision or
            // the exact receipt revision, but never an unrelated head.
            if heartbeat.fence.current_revision != sources[index].revision
                && heartbeat.fence.current_revision != output.revision
            {
                return Err(TradeHandoffError::LeaseNotHealthy);
            }
            heartbeat.validate(sources[index], heartbeat.fence.current_revision, now_ms)?;
            publish_fences[index] = Some(heartbeat.fence);
        }
        if let Some(existing) = self.receipt {
            if existing != receipt {
                return Err(TradeHandoffError::ReceiptMismatch);
            }
        } else {
            self.receipt = Some(receipt);
        }
        self.publish_fences = publish_fences;
        self.phase = TradePhase::Adopting;
        Ok(())
    }

    /// Confirms one local atomic replacement. The session layer performs the
    /// actual fixed-file writes before calling this method; it must retain the
    /// old source until those writes and this transition both succeed.
    pub fn adopt(
        &mut self,
        participant: usize,
        output: TradePublishedHead,
        heartbeat: TradeHeartbeat,
        now_ms: u64,
    ) -> Result<(), TradeHandoffError> {
        if self.phase != TradePhase::Adopting || participant >= TRADE_PARTICIPANTS {
            return Err(TradeHandoffError::InvalidPhase);
        }
        let source = self.sources[participant].ok_or(TradeHandoffError::ReplacementMismatch)?;
        let receipt = self.receipt.ok_or(TradeHandoffError::ReplacementMismatch)?;
        if output != receipt.outputs[participant] {
            return Err(TradeHandoffError::ReplacementMismatch);
        }
        heartbeat.validate(source, output.revision, now_ms)?;
        if self.adopted[participant] {
            return Ok(());
        }
        self.adopted[participant] = true;
        if self.adopted.iter().all(|adopted| *adopted) {
            self.phase = TradePhase::Complete;
        }
        Ok(())
    }

    /// Publication has not happened, so abandoning the pair is safe. Once a
    /// receipt exists, callers must recover and adopt it instead of silently
    /// reopening either client with the old head.
    pub fn abort(&mut self) -> Result<(), TradeHandoffError> {
        match self.phase {
            TradePhase::Quiescing | TradePhase::Staging => {
                self.phase = TradePhase::Aborted;
                Ok(())
            }
            // Once publication has started, the server may have committed
            // even when the response was lost.  Only an authoritative status
            // or cancellation adapter may eventually resolve that state.
            TradePhase::Publishing | TradePhase::Adopting | TradePhase::Complete => {
                Err(TradeHandoffError::InvalidPhase)
            }
            TradePhase::Aborted => Ok(()),
        }
    }

    #[must_use]
    pub fn recovery_journal(&self) -> TradeRecoveryJournal {
        TradeRecoveryJournal {
            offer_id: self.offer_id,
            group_id: self.group_id,
            idempotency_key: self.idempotency_key,
            members: self.members,
            phase: self.phase,
            sources: self.sources,
            publish_fences: self.publish_fences,
            receipt: self.receipt,
            adopted: self.adopted,
        }
    }

    /// Rehydrates a local handoff after a launcher restart. A published
    /// receipt always re-enters adoption, so the old source remains the only
    /// usable fallback until both new heads are verified.
    pub fn recover(journal: TradeRecoveryJournal) -> Result<Self, TradeHandoffError> {
        if journal.members[0] == journal.members[1]
            || journal.sources.iter().enumerate().any(|(index, source)| {
                source.is_some_and(|source| source.validate(journal.members[index]).is_err())
            })
        {
            return Err(TradeHandoffError::RecoveryMismatch);
        }
        if journal.adopted.iter().any(|adopted| *adopted) && journal.receipt.is_none() {
            return Err(TradeHandoffError::RecoveryMismatch);
        }
        if let Some(receipt) = journal.receipt {
            if receipt.offer_id != journal.offer_id
                || receipt.idempotency_key != journal.idempotency_key
                || journal.sources.iter().enumerate().any(|(index, source)| {
                    let Some(source) = source else {
                        return true;
                    };
                    let output = receipt.outputs[index];
                    output.character_id != source.character_id
                        || output.snapshot_id == source.snapshot_id
                        || Some(output.revision) != source.revision.next().ok()
                })
            {
                return Err(TradeHandoffError::RecoveryMismatch);
            }
        }
        let sources_complete = journal.sources.iter().all(Option::is_some);
        let source_count = journal
            .sources
            .iter()
            .filter(|source| source.is_some())
            .count();
        let publish_fences_complete = journal.publish_fences.iter().all(Option::is_some);
        let no_publish_fences = journal.publish_fences == [None, None];
        let phase_valid = match journal.phase {
            TradePhase::Quiescing => {
                source_count <= 1
                    && journal.receipt.is_none()
                    && journal.adopted == [false, false]
                    && no_publish_fences
            }
            TradePhase::Staging => {
                sources_complete
                    && journal.receipt.is_none()
                    && journal.adopted == [false, false]
                    && no_publish_fences
            }
            TradePhase::Publishing => {
                sources_complete
                    && journal.receipt.is_none()
                    && journal.adopted == [false, false]
                    && publish_fences_complete
            }
            TradePhase::Adopting => {
                journal.receipt.is_some()
                    && publish_fences_complete
                    && !journal.adopted.iter().all(|adopted| *adopted)
            }
            TradePhase::Complete => {
                journal.receipt.is_some()
                    && publish_fences_complete
                    && journal.adopted.iter().all(|adopted| *adopted)
            }
            TradePhase::Aborted => {
                journal.receipt.is_none() && journal.adopted == [false, false] && no_publish_fences
            }
        };
        if !phase_valid {
            return Err(TradeHandoffError::RecoveryMismatch);
        }
        for (index, fence) in journal.publish_fences.into_iter().enumerate() {
            if let Some(fence) = fence {
                let Some(source) = journal.sources[index] else {
                    return Err(TradeHandoffError::RecoveryMismatch);
                };
                if fence.session_id != source.session_id
                    || fence.character_id != source.character_id
                    || fence.client_instance_id != source.fence.client_instance_id
                    || fence.session_epoch != source.fence.session_epoch
                {
                    return Err(TradeHandoffError::RecoveryMismatch);
                }
                let fence_revision_valid = fence.current_revision == source.revision
                    || journal.receipt.is_some_and(|receipt| {
                        fence.current_revision == receipt.outputs[index].revision
                    });
                if !fence_revision_valid {
                    return Err(TradeHandoffError::RecoveryMismatch);
                }
            }
        }
        Ok(Self {
            offer_id: journal.offer_id,
            group_id: journal.group_id,
            idempotency_key: journal.idempotency_key,
            members: journal.members,
            phase: journal.phase,
            sources: journal.sources,
            publish_fences: journal.publish_fences,
            receipt: journal.receipt,
            adopted: journal.adopted,
        })
    }

    /// Retains the session identity while allowing a reconnecting adapter to
    /// prove that its source is still the anchored head.
    pub fn reconnect_source(
        &self,
        participant: usize,
        source: TradeSourceHead,
        heartbeat: TradeHeartbeat,
        now_ms: u64,
    ) -> Result<(), TradeHandoffError> {
        if participant >= TRADE_PARTICIPANTS {
            return Err(TradeHandoffError::SourceMismatch);
        }
        if self.phase == TradePhase::Publishing && self.receipt.is_none() {
            // The publication result is unknown.  Releasing either client at
            // its old head could fork it away from a server commit that
            // succeeded before the response was lost.
            return Err(TradeHandoffError::InvalidPhase);
        }
        let expected = self.sources[participant].ok_or(TradeHandoffError::SourceMismatch)?;
        if expected != source {
            return Err(TradeHandoffError::SourceMismatch);
        }
        let revision = self
            .receipt
            .map(|receipt| receipt.outputs[participant].revision)
            .unwrap_or(source.revision);
        heartbeat.validate(source, revision, now_ms)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use coop_cloud::ClientInstanceId;
    use uuid::Uuid;

    fn id<T>(make: impl FnOnce(Uuid) -> Result<T, coop_cloud::IdError>) -> T {
        make(Uuid::from_u128(1)).unwrap()
    }

    fn idv<T>(make: impl FnOnce(Uuid) -> Result<T, coop_cloud::IdError>, value: u128) -> T {
        make(Uuid::from_u128(value)).unwrap()
    }

    fn fixtures() -> ([CharacterId; 2], GroupId, TradeOfferId, IdempotencyKey) {
        let a = id(CharacterId::new);
        let b = id(|uuid| CharacterId::new(Uuid::from_u128(uuid.as_u128() + 1)));
        (
            [a, b],
            id(GroupId::new),
            id(TradeOfferId::new),
            id(IdempotencyKey::new),
        )
    }

    fn source(character_id: CharacterId, revision: u64) -> TradeSourceHead {
        let session_id = id(SessionId::new);
        let client = id(ClientInstanceId::new);
        let epoch = coop_cloud::SessionEpoch::new(3).unwrap();
        let fence = LeaseFence::new(
            session_id,
            character_id,
            Revision::new(revision),
            epoch,
            client,
        );
        TradeSourceHead {
            character_id,
            session_id,
            snapshot_id: id(SnapshotId::new),
            revision: Revision::new(revision),
            fence,
            save_sha256: Sha256Digest::of_bytes(b"save"),
            pending_commits_sha256: Sha256Digest::of_bytes(b"[]"),
        }
    }

    fn heartbeat(source: TradeSourceHead, revision: Revision) -> TradeHeartbeat {
        TradeHeartbeat {
            fence: LeaseFence {
                current_revision: revision,
                ..source.fence
            },
            expires_at_ms: 10_000,
        }
    }

    #[test]
    fn both_quiesced_heads_fence_ordinary_saves_and_stage_exact_sources() {
        let (members, group, offer, idem) = fixtures();
        let mut handoff = TradeHandoff::begin(offer, group, idem, members).unwrap();
        let left = source(members[0], 4);
        let right = source(members[1], 9);
        assert!(handoff.ordinary_save_permitted(0));
        handoff
            .record_quiesced(0, left, heartbeat(left, left.revision), 100)
            .unwrap();
        assert!(!handoff.ordinary_save_permitted(0));
        handoff
            .record_quiesced(1, right, heartbeat(right, right.revision), 100)
            .unwrap();
        assert_eq!(handoff.phase(), TradePhase::Staging);
        let token = handoff.stage_token().unwrap();
        handoff
            .mark_staged(
                token,
                [
                    heartbeat(left, left.revision),
                    heartbeat(right, right.revision),
                ],
                100,
            )
            .unwrap();
        assert_eq!(handoff.phase(), TradePhase::Publishing);
        assert_eq!(
            handoff.require_ordinary_save_permit(0),
            Err(TradeHandoffError::SaveFenced)
        );
    }

    #[test]
    fn failed_second_stage_heartbeat_leaves_staging_journal_unchanged() {
        let (members, group, offer, idem) = fixtures();
        let mut handoff = TradeHandoff::begin(offer, group, idem, members).unwrap();
        let left = source(members[0], 4);
        let right = source(members[1], 9);
        handoff
            .record_quiesced(0, left, heartbeat(left, left.revision), 100)
            .unwrap();
        handoff
            .record_quiesced(1, right, heartbeat(right, right.revision), 100)
            .unwrap();
        let before = handoff.recovery_journal();
        assert_eq!(
            handoff.mark_staged(
                handoff.stage_token().unwrap(),
                [
                    heartbeat(left, left.revision),
                    heartbeat(right, Revision::new(8))
                ],
                100,
            ),
            Err(TradeHandoffError::LeaseNotHealthy)
        );
        assert_eq!(handoff.recovery_journal(), before);
        assert_eq!(
            TradeHandoff::recover(before).unwrap().phase(),
            TradePhase::Staging
        );
    }

    #[test]
    fn failed_second_publish_heartbeat_leaves_publishing_journal_unchanged() {
        let (members, group, offer, idem) = fixtures();
        let mut handoff = TradeHandoff::begin(offer, group, idem, members).unwrap();
        let left = source(members[0], 4);
        let right = source(members[1], 9);
        handoff
            .record_quiesced(0, left, heartbeat(left, left.revision), 100)
            .unwrap();
        handoff
            .record_quiesced(1, right, heartbeat(right, right.revision), 100)
            .unwrap();
        handoff
            .mark_staged(
                handoff.stage_token().unwrap(),
                [
                    heartbeat(left, left.revision),
                    heartbeat(right, right.revision),
                ],
                100,
            )
            .unwrap();
        let receipt = TradeCommitReceipt {
            offer_id: offer,
            idempotency_key: idem,
            outputs: [
                TradePublishedHead {
                    character_id: members[0],
                    snapshot_id: idv(SnapshotId::new, 11),
                    revision: Revision::new(5),
                    save_sha256: Sha256Digest::of_bytes(b"left-new"),
                    pending_commits_sha256: Sha256Digest::of_bytes(b"[]"),
                },
                TradePublishedHead {
                    character_id: members[1],
                    snapshot_id: idv(SnapshotId::new, 12),
                    revision: Revision::new(10),
                    save_sha256: Sha256Digest::of_bytes(b"right-new"),
                    pending_commits_sha256: Sha256Digest::of_bytes(b"[]"),
                },
            ],
        };
        let before = handoff.recovery_journal();
        assert_eq!(
            handoff.mark_published(
                receipt,
                [
                    heartbeat(left, left.revision),
                    heartbeat(right, Revision::new(8))
                ],
                100,
            ),
            Err(TradeHandoffError::LeaseNotHealthy)
        );
        assert_eq!(handoff.recovery_journal(), before);
        assert_eq!(
            TradeHandoff::recover(before).unwrap().phase(),
            TradePhase::Publishing
        );
    }

    #[test]
    fn publication_is_paired_and_replayed_receipts_are_idempotent() {
        let (members, group, offer, idem) = fixtures();
        let mut handoff = TradeHandoff::begin(offer, group, idem, members).unwrap();
        let left = source(members[0], 4);
        let right = source(members[1], 9);
        handoff
            .record_quiesced(0, left, heartbeat(left, left.revision), 100)
            .unwrap();
        handoff
            .record_quiesced(1, right, heartbeat(right, right.revision), 100)
            .unwrap();
        handoff
            .mark_staged(
                handoff.stage_token().unwrap(),
                [
                    heartbeat(left, left.revision),
                    heartbeat(right, right.revision),
                ],
                100,
            )
            .unwrap();
        let receipt = TradeCommitReceipt {
            offer_id: offer,
            idempotency_key: idem,
            outputs: [
                TradePublishedHead {
                    character_id: members[0],
                    snapshot_id: idv(SnapshotId::new, 11),
                    revision: Revision::new(5),
                    save_sha256: Sha256Digest::of_bytes(b"left-new"),
                    pending_commits_sha256: Sha256Digest::of_bytes(b"[]"),
                },
                TradePublishedHead {
                    character_id: members[1],
                    snapshot_id: idv(SnapshotId::new, 12),
                    revision: Revision::new(10),
                    save_sha256: Sha256Digest::of_bytes(b"right-new"),
                    pending_commits_sha256: Sha256Digest::of_bytes(b"[]"),
                },
            ],
        };
        handoff
            .mark_published(
                receipt,
                [
                    heartbeat(left, left.revision),
                    heartbeat(right, right.revision),
                ],
                100,
            )
            .unwrap();
        handoff
            .mark_published(
                receipt,
                [
                    heartbeat(left, left.revision),
                    heartbeat(right, right.revision),
                ],
                100,
            )
            .unwrap();
        assert_eq!(handoff.phase(), TradePhase::Adopting);
        let new_left = receipt.outputs[0];
        let new_right = receipt.outputs[1];
        assert_eq!(
            handoff.adopt(0, new_left, heartbeat(left, new_left.revision), 100),
            Ok(())
        );
        assert_eq!(
            handoff.adopt(1, new_right, heartbeat(right, new_right.revision), 100),
            Ok(())
        );
        assert_eq!(handoff.phase(), TradePhase::Complete);
        assert!(handoff.ordinary_save_permitted(0));
        assert!(handoff.ordinary_save_permitted(1));
    }

    #[test]
    fn lost_publish_response_keeps_pair_fenced_until_authoritative_resolution() {
        let (members, group, offer, idem) = fixtures();
        let mut handoff = TradeHandoff::begin(offer, group, idem, members).unwrap();
        let left = source(members[0], 4);
        let right = source(members[1], 9);
        handoff
            .record_quiesced(0, left, heartbeat(left, left.revision), 100)
            .unwrap();
        handoff
            .record_quiesced(1, right, heartbeat(right, right.revision), 100)
            .unwrap();
        handoff
            .mark_staged(
                handoff.stage_token().unwrap(),
                [
                    heartbeat(left, left.revision),
                    heartbeat(right, right.revision),
                ],
                100,
            )
            .unwrap();

        let journal = handoff.recovery_journal();
        assert_eq!(journal.phase, TradePhase::Publishing);
        assert!(journal.publish_fences.iter().all(Option::is_some));
        let mut recovered = TradeHandoff::recover(journal.clone()).unwrap();
        assert_eq!(recovered.phase(), TradePhase::Publishing);
        assert_eq!(
            recovered.recovery_journal().publish_fences,
            journal.publish_fences
        );
        assert_eq!(recovered.abort(), Err(TradeHandoffError::InvalidPhase));
        assert!(!recovered.ordinary_save_permitted(0));
        assert_eq!(
            recovered.reconnect_source(0, left, heartbeat(left, left.revision), 100),
            Err(TradeHandoffError::InvalidPhase)
        );
    }

    #[test]
    fn recovery_rejects_phase_or_adoption_inconsistency() {
        let (members, group, offer, idem) = fixtures();
        let mut handoff = TradeHandoff::begin(offer, group, idem, members).unwrap();
        let left = source(members[0], 4);
        let right = source(members[1], 9);
        handoff
            .record_quiesced(0, left, heartbeat(left, left.revision), 100)
            .unwrap();
        handoff
            .record_quiesced(1, right, heartbeat(right, right.revision), 100)
            .unwrap();
        let journal = handoff.recovery_journal();
        let mut wrong_phase = journal.clone();
        wrong_phase.phase = TradePhase::Quiescing;
        assert_eq!(
            TradeHandoff::recover(wrong_phase),
            Err(TradeHandoffError::RecoveryMismatch)
        );
        let mut adopted_without_receipt = journal;
        adopted_without_receipt.adopted[0] = true;
        assert_eq!(
            TradeHandoff::recover(adopted_without_receipt),
            Err(TradeHandoffError::RecoveryMismatch)
        );
    }

    #[test]
    fn abort_restores_ordinary_saves_only_before_publication() {
        let (members, group, offer, idem) = fixtures();
        let mut quiescing = TradeHandoff::begin(offer, group, idem, members).unwrap();
        quiescing.abort().unwrap();
        assert_eq!(quiescing.phase(), TradePhase::Aborted);
        assert!(quiescing.ordinary_save_permitted(0));
        assert!(quiescing.ordinary_save_permitted(1));

        let mut staging = TradeHandoff::begin(offer, group, idem, members).unwrap();
        let left = source(members[0], 4);
        let right = source(members[1], 9);
        staging
            .record_quiesced(0, left, heartbeat(left, left.revision), 100)
            .unwrap();
        staging
            .record_quiesced(1, right, heartbeat(right, right.revision), 100)
            .unwrap();
        staging.abort().unwrap();
        assert_eq!(staging.phase(), TradePhase::Aborted);
        assert!(staging.ordinary_save_permitted(0));
        assert!(staging.ordinary_save_permitted(1));
    }

    #[test]
    fn recovery_with_receipt_never_reopens_the_old_head() {
        let (members, group, offer, idem) = fixtures();
        let mut handoff = TradeHandoff::begin(offer, group, idem, members).unwrap();
        let left = source(members[0], 4);
        let right = source(members[1], 9);
        handoff
            .record_quiesced(0, left, heartbeat(left, left.revision), 100)
            .unwrap();
        handoff
            .record_quiesced(1, right, heartbeat(right, right.revision), 100)
            .unwrap();
        handoff
            .mark_staged(
                handoff.stage_token().unwrap(),
                [
                    heartbeat(left, left.revision),
                    heartbeat(right, right.revision),
                ],
                100,
            )
            .unwrap();
        let receipt = TradeCommitReceipt {
            offer_id: offer,
            idempotency_key: idem,
            outputs: [
                TradePublishedHead {
                    character_id: members[0],
                    snapshot_id: idv(SnapshotId::new, 11),
                    revision: Revision::new(5),
                    save_sha256: Sha256Digest::of_bytes(b"left"),
                    pending_commits_sha256: Sha256Digest::of_bytes(b"[]"),
                },
                TradePublishedHead {
                    character_id: members[1],
                    snapshot_id: idv(SnapshotId::new, 12),
                    revision: Revision::new(10),
                    save_sha256: Sha256Digest::of_bytes(b"right"),
                    pending_commits_sha256: Sha256Digest::of_bytes(b"[]"),
                },
            ],
        };
        handoff
            .mark_published(
                receipt,
                [
                    heartbeat(left, left.revision),
                    heartbeat(right, right.revision),
                ],
                100,
            )
            .unwrap();
        let mut recovered = TradeHandoff::recover(handoff.recovery_journal()).unwrap();
        assert_eq!(recovered.phase(), TradePhase::Adopting);
        assert_eq!(recovered.abort(), Err(TradeHandoffError::InvalidPhase));
        assert!(
            recovered
                .reconnect_source(0, left, heartbeat(left, receipt.outputs[0].revision), 100)
                .is_ok()
        );
    }
}
