Cormoria_GastreeCity_House3_MapScripts::
	.byte 0


Cormoria_GastreeCity_House3_NPC1::
# 4 "data//maps/GastreeCity_House3/scripts.pory"
	msgbox Cormoria_GastreeCity_House3_NPC1_Text_0, MSGBOX_NPC
	end


Cormoria_GastreeCity_House3_NPC1_Text_0:
# 4 "data//maps/GastreeCity_House3/scripts.pory"
	.string "The big news of the week is Professor\n"
	.string "Tenebris disappearing. She gave my son\l"
	.string "his first Pokémon - a Bergmite!\p"
	.string "...\p"
	.string "Ever since his mother left, he's always\n"
	.string "outside, training with Bergmite.$"
