Cormoria_FennilahlTown_House2_MapScripts::
	.byte 0


Cormoria_FennilahlTown_House2_NPC::
# 5 "data//maps/FennilahlTown_House2/scripts.pory"
	msgbox Cormoria_FennilahlTown_House2_NPC_Text_0, MSGBOX_NPC
	end


Cormoria_FennilahlTown_House2_NPC_Text_0:
# 5 "data//maps/FennilahlTown_House2/scripts.pory"
	.string "I just moved into my dream retirement\n"
	.string "house! But my furniture hasn't arrived\l"
	.string "yet.$"
